import type { TemplateDefinition } from './types';

export const TEMPLATES: TemplateDefinition[] = [
  // ─── EDITORIAL (default) ──────────────────────────────────────────────────
  // Matches the reference: small red italic supporting words + massive red bold-italic hero
  {
    id: 'editorial',
    name: 'EDITORIAL',
    description: 'Large red bold-italic hero word with small supporting words. Classic editorial typography.',
    fontFamily: '"Playfair Display", serif',
    fontWeight: 400,
    fontStyle: 'italic',
    textTransform: 'none',
    baseColor: '#cc1111',
    baseSize: 28,
    baseOpacity: 0.85,
    heroColor: '#cc1111',
    heroScale: 2.8,
    heroFontFamily: '"Playfair Display", serif',
    heroFontWeight: 700,
    heroFontStyle: 'italic',
    accentColor: '#cc1111',
    alignment: 'center',
    layoutType: 'editorial',
    letterSpacing: '0.01em',
    lineHeight: 1.0,
    shadow: 'none',
    entranceAnimation: 'fade-up',
    wordActivation: 'none',
    animationSpeed: 1.0,
    captionDepth: 'front',
    position: 'center',
  },

  // ─── EDITORIAL DARK ───────────────────────────────────────────────────────
  // Dark bg version: white supporting, red hero
  {
    id: 'editorial-dark',
    name: 'EDITORIAL DARK',
    description: 'White small supporting words, large red hero. For dark video backgrounds.',
    fontFamily: '"Playfair Display", serif',
    fontWeight: 400,
    fontStyle: 'italic',
    textTransform: 'none',
    baseColor: '#ffffff',
    baseSize: 28,
    baseOpacity: 0.85,
    heroColor: '#e02020',
    heroScale: 2.8,
    heroFontFamily: '"Playfair Display", serif',
    heroFontWeight: 700,
    heroFontStyle: 'italic',
    accentColor: '#cccccc',
    alignment: 'center',
    layoutType: 'editorial',
    letterSpacing: '0.01em',
    lineHeight: 1.0,
    shadow: '0px 2px 12px rgba(0,0,0,0.4)',
    entranceAnimation: 'fade-up',
    wordActivation: 'none',
    animationSpeed: 1.0,
    captionDepth: 'front',
    position: 'center',
  },

  // ─── SERIF BLOOM ─────────────────────────────────────────────────────────
  {
    id: 'serif-bloom',
    name: 'SERIF BLOOM',
    description: 'Elegant serif typography with warm tones and editorial composition.',
    fontFamily: '"Playfair Display", serif',
    fontWeight: 600,
    fontStyle: 'italic',
    textTransform: 'none',
    baseColor: '#f2eae1',
    baseSize: 42,
    baseOpacity: 0.8,
    heroColor: '#ffffff',
    heroScale: 1.6,
    heroFontFamily: '"Playfair Display", serif',
    heroFontWeight: 800,
    heroFontStyle: 'italic',
    accentColor: '#d6c5b3',
    alignment: 'center',
    layoutType: 'inline',
    letterSpacing: '0.02em',
    lineHeight: 1.2,
    shadow: '0px 2px 8px rgba(0,0,0,0.4)',
    entranceAnimation: 'fade',
    wordActivation: 'color-fill',
    animationSpeed: 1.0,
    captionDepth: 'mixed',
    position: 'center',
  },

  // ─── SIGNAL ───────────────────────────────────────────────────────────────
  {
    id: 'signal',
    name: 'SIGNAL',
    description: 'Bold sans-serif, compact word grouping, strong readability.',
    fontFamily: '"Geist", sans-serif',
    fontWeight: 700,
    fontStyle: 'normal',
    textTransform: 'uppercase',
    baseColor: '#ffffff',
    baseSize: 48,
    baseOpacity: 0.9,
    heroColor: '#00ffaa',
    heroScale: 1.2,
    heroFontWeight: 900,
    heroFontStyle: 'normal',
    accentColor: '#a0a0a0',
    alignment: 'center',
    layoutType: 'inline',
    letterSpacing: '-0.02em',
    lineHeight: 1.1,
    shadow: '0px 4px 12px rgba(0,0,0,0.6)',
    entranceAnimation: 'slide-up',
    wordActivation: 'color-fill',
    animationSpeed: 1.0,
    captionDepth: 'front',
    position: 'bottom',
  },

  // ─── CLEAN FOCUS ──────────────────────────────────────────────────────────
  {
    id: 'clean-focus',
    name: 'CLEAN FOCUS',
    description: 'Bold modern sans, minimal composition, single-word emphasis.',
    fontFamily: '"Geist", sans-serif',
    fontWeight: 600,
    fontStyle: 'normal',
    textTransform: 'none',
    baseColor: '#e0e0e0',
    baseSize: 40,
    baseOpacity: 0.7,
    heroColor: '#ffffff',
    heroScale: 1.3,
    heroFontWeight: 800,
    heroFontStyle: 'normal',
    accentColor: '#9b82f3',
    alignment: 'center',
    layoutType: 'inline',
    letterSpacing: '0',
    lineHeight: 1.3,
    shadow: 'none',
    entranceAnimation: 'blur-in',
    wordActivation: 'color-fill',
    animationSpeed: 1.0,
    captionDepth: 'front',
    position: 'bottom',
  },

  // ─── COMIC PUNCH ──────────────────────────────────────────────────────────
  {
    id: 'comic-punch',
    name: 'COMIC PUNCH',
    description: 'Large display typography, uppercase hero words, energetic scale.',
    fontFamily: '"JetBrains Mono", monospace',
    fontWeight: 800,
    fontStyle: 'normal',
    textTransform: 'uppercase',
    baseColor: '#ffffff',
    baseSize: 52,
    baseOpacity: 1,
    heroColor: '#ffcc00',
    heroScale: 1.4,
    heroFontWeight: 800,
    heroFontStyle: 'normal',
    accentColor: '#ffffff',
    alignment: 'center',
    layoutType: 'inline',
    letterSpacing: '0.05em',
    lineHeight: 1.1,
    outline: '3px solid #000000',
    shadow: '4px 4px 0px #000000',
    entranceAnimation: 'bounce',
    wordActivation: 'scale-up',
    animationSpeed: 0.8,
    captionDepth: 'front',
    position: 'center',
  },

  // ─── POSTER ───────────────────────────────────────────────────────────────
  {
    id: 'poster',
    name: 'POSTER',
    description: 'Poster-like layout, very large hero word, asymmetric positioning.',
    fontFamily: '"Geist", sans-serif',
    fontWeight: 800,
    fontStyle: 'normal',
    textTransform: 'uppercase',
    baseColor: '#ffffff',
    baseSize: 32,
    baseOpacity: 0.9,
    heroColor: '#ffffff',
    heroScale: 2.5,
    heroFontWeight: 900,
    heroFontStyle: 'normal',
    accentColor: '#cccccc',
    alignment: 'left',
    layoutType: 'asymmetric',
    letterSpacing: '-0.04em',
    lineHeight: 0.9,
    shadow: '0px 8px 24px rgba(0,0,0,0.5)',
    entranceAnimation: 'reveal',
    wordActivation: 'none',
    animationSpeed: 1.2,
    captionDepth: 'behind-subject',
    position: 'center',
  },

  // ─── AMBER STACK ──────────────────────────────────────────────────────────
  {
    id: 'amber-stack',
    name: 'AMBER STACK',
    description: 'Stacked layout, dominant hero word, amber hero, vertical hierarchy.',
    fontFamily: '"Geist", sans-serif',
    fontWeight: 700,
    fontStyle: 'normal',
    textTransform: 'uppercase',
    baseColor: '#ffffff',
    baseSize: 44,
    baseOpacity: 0.9,
    heroColor: '#ff8c00',
    heroScale: 1.6,
    heroFontWeight: 900,
    heroFontStyle: 'normal',
    accentColor: '#ffb77d',
    alignment: 'center',
    layoutType: 'stacked',
    letterSpacing: '0.01em',
    lineHeight: 1.0,
    shadow: '0px 4px 16px rgba(0,0,0,0.8)',
    entranceAnimation: 'slide-up',
    wordActivation: 'color-fill',
    animationSpeed: 1.0,
    captionDepth: 'behind-subject',
    position: 'bottom',
  },

  // ─── EDITORIAL FRAME ──────────────────────────────────────────────────────
  {
    id: 'editorial-frame',
    name: 'EDITORIAL FRAME',
    description: 'Large hero word, smaller supporting words, clean negative space.',
    fontFamily: '"Cormorant Garamond", serif',
    fontWeight: 400,
    fontStyle: 'normal',
    textTransform: 'none',
    baseColor: '#ffffff',
    baseSize: 28,
    baseOpacity: 0.7,
    heroColor: '#ffffff',
    heroScale: 2.2,
    heroFontFamily: '"Cormorant Garamond", serif',
    heroFontWeight: 700,
    heroFontStyle: 'italic',
    accentColor: '#a0a0a0',
    alignment: 'left',
    layoutType: 'editorial',
    letterSpacing: '0',
    lineHeight: 1.1,
    shadow: '0px 2px 10px rgba(0,0,0,0.3)',
    entranceAnimation: 'fade',
    wordActivation: 'none',
    animationSpeed: 1.3,
    captionDepth: 'mixed',
    position: 'bottom-left',
  },

  // ─── PREMIERE ─────────────────────────────────────────────────────────────
  {
    id: 'premiere',
    name: 'PREMIERE',
    description: 'Dramatic serif hero, cinematic composition, red hero treatment.',
    fontFamily: '"EB Garamond", serif',
    fontWeight: 400,
    fontStyle: 'italic',
    textTransform: 'none',
    baseColor: '#ffffff',
    baseSize: 32,
    baseOpacity: 0.85,
    heroColor: '#cc1111',
    heroScale: 2.2,
    heroFontFamily: '"Playfair Display", serif',
    heroFontWeight: 800,
    heroFontStyle: 'italic',
    accentColor: '#e0e0e0',
    alignment: 'center',
    layoutType: 'editorial',
    letterSpacing: '0.02em',
    lineHeight: 1.1,
    shadow: '0px 4px 20px rgba(0,0,0,0.6)',
    entranceAnimation: 'fade-up',
    wordActivation: 'none',
    animationSpeed: 1.2,
    captionDepth: 'behind-subject',
    position: 'center',
  },

  // ─── NEW COMPOSITION TEMPLATES ───────────────────────────────────────────
  {
    id: 'hero-interruption',
    name: 'HERO INTERRUPTION',
    description: 'Hero word physically breaks the sentence with generous overlap.',
    fontFamily: '"Geist", sans-serif',
    fontWeight: 600,
    fontStyle: 'normal',
    textTransform: 'uppercase',
    baseColor: '#ffffff',
    baseSize: 32,
    baseOpacity: 0.9,
    heroColor: '#ff0055',
    heroScale: 2.5,
    heroFontWeight: 900,
    heroFontStyle: 'italic',
    accentColor: '#cccccc',
    alignment: 'center',
    layoutType: 'hero-interruption',
    letterSpacing: '-0.02em',
    lineHeight: 1.0,
    shadow: '0px 4px 12px rgba(0,0,0,0.6)',
    entranceAnimation: 'rise',
    heroEntranceAnimation: 'punch-in',
    wordActivation: 'none',
    animationSpeed: 1.0,
    captionDepth: 'front',
    position: 'center',
    numberEmphasis: 'auto',
  },
  {
    id: 'corner-hero-tl',
    name: 'CORNER HERO',
    description: 'Supporting text at the bottom, hero pinned to top-left.',
    fontFamily: '"Geist", sans-serif',
    fontWeight: 500,
    fontStyle: 'normal',
    textTransform: 'none',
    baseColor: '#ffffff',
    baseSize: 36,
    baseOpacity: 0.8,
    heroColor: '#ffffff',
    heroScale: 2.0,
    heroFontWeight: 800,
    heroFontStyle: 'normal',
    accentColor: '#aaaaaa',
    alignment: 'center',
    layoutType: 'corner-hero',
    heroPosition: 'corner-tl',
    letterSpacing: '0',
    lineHeight: 1.2,
    shadow: 'none',
    entranceAnimation: 'fade-up',
    heroEntranceAnimation: 'pop-in',
    wordActivation: 'none',
    animationSpeed: 1.0,
    captionDepth: 'front',
    position: 'bottom',
    numberEmphasis: 'always',
    countUpEnabled: true,
  },
  {
    id: 'split-hero',
    name: 'SPLIT HERO',
    description: 'Words distributed vertically. Excellent for short phrases.',
    fontFamily: '"Playfair Display", serif',
    fontWeight: 700,
    fontStyle: 'italic',
    textTransform: 'none',
    baseColor: '#ffffff',
    baseSize: 42,
    baseOpacity: 1.0,
    heroColor: '#e02020',
    heroScale: 1.5,
    heroFontWeight: 800,
    heroFontStyle: 'italic',
    accentColor: '#ffffff',
    alignment: 'center',
    layoutType: 'split-hero',
    letterSpacing: '0.02em',
    lineHeight: 1.0,
    shadow: '0px 2px 10px rgba(0,0,0,0.5)',
    entranceAnimation: 'stagger',
    wordActivation: 'none',
    animationSpeed: 1.2,
    captionDepth: 'mixed',
    position: 'center',
    numberEmphasis: 'auto',
  },
  {
    id: 'giant-bg',
    name: 'GIANT WORD',
    description: 'Huge ghosted background word behind the main caption.',
    fontFamily: '"Geist", sans-serif',
    fontWeight: 700,
    fontStyle: 'normal',
    textTransform: 'uppercase',
    baseColor: '#ffffff',
    baseSize: 32,
    baseOpacity: 1.0,
    heroColor: '#ffffff',
    heroScale: 1.5,
    heroFontWeight: 900,
    heroFontStyle: 'normal',
    accentColor: '#cccccc',
    alignment: 'center',
    layoutType: 'giant-bg',
    bgWordOpacity: 0.15,
    bgWordBlur: 4,
    bgWordSize: 180,
    letterSpacing: '-0.02em',
    lineHeight: 1.1,
    shadow: '0px 2px 8px rgba(0,0,0,0.8)',
    entranceAnimation: 'slide-up',
    heroEntranceAnimation: 'fade',
    wordActivation: 'color-fill',
    animationSpeed: 1.0,
    captionDepth: 'front',
    position: 'center',
    numberEmphasis: 'auto',
  },
  {
    id: 'sentence-hero',
    name: 'SENTENCE HERO',
    description: 'Full sentence kept readable with one massive hero word above.',
    fontFamily: '"Geist", sans-serif',
    fontWeight: 500,
    fontStyle: 'normal',
    textTransform: 'none',
    baseColor: '#ffffff',
    baseSize: 32,
    baseOpacity: 0.8,
    heroColor: '#00ffaa',
    heroScale: 2.2,
    heroFontWeight: 900,
    heroFontStyle: 'normal',
    accentColor: '#ffffff',
    alignment: 'center',
    layoutType: 'sentence-hero',
    letterSpacing: '0',
    lineHeight: 1.2,
    shadow: '0px 4px 12px rgba(0,0,0,0.6)',
    entranceAnimation: 'fade-up',
    heroEntranceAnimation: 'elastic-rise',
    wordActivation: 'none',
    animationSpeed: 1.0,
    captionDepth: 'front',
    position: 'bottom',
    numberEmphasis: 'always',
    countUpEnabled: true,
  },
  {
    id: 'hero-micro',
    name: 'HERO + MICRO',
    description: 'Massive hero word with tiny contextual labels.',
    fontFamily: '"Geist", sans-serif',
    fontWeight: 700,
    fontStyle: 'uppercase',
    textTransform: 'uppercase',
    baseColor: '#aaaaaa',
    baseSize: 24,
    baseOpacity: 1.0,
    heroColor: '#ffffff',
    heroScale: 3.5,
    heroFontWeight: 900,
    heroFontStyle: 'normal',
    accentColor: '#ffffff',
    alignment: 'center',
    layoutType: 'hero-micro',
    letterSpacing: '0.05em',
    lineHeight: 1.0,
    shadow: 'none',
    entranceAnimation: 'fade',
    heroEntranceAnimation: 'zoom-in',
    wordActivation: 'none',
    animationSpeed: 1.2,
    captionDepth: 'behind-subject',
    position: 'center',
    numberEmphasis: 'always',
    countUpEnabled: true,
  },
  {
    id: 'word-collision',
    name: 'WORD COLLISION',
    description: 'Words enter from opposite directions and collide.',
    fontFamily: '"Geist", sans-serif',
    fontWeight: 900,
    fontStyle: 'normal',
    textTransform: 'uppercase',
    baseColor: '#ffffff',
    baseSize: 48,
    baseOpacity: 1.0,
    heroColor: '#ffcc00',
    heroScale: 1.2,
    heroFontWeight: 900,
    heroFontStyle: 'italic',
    accentColor: '#ffffff',
    alignment: 'center',
    layoutType: 'word-collision',
    letterSpacing: '-0.03em',
    lineHeight: 1.0,
    shadow: '4px 4px 0px rgba(0,0,0,1)',
    entranceAnimation: 'collision-left',
    heroEntranceAnimation: 'collision-right',
    wordActivation: 'none',
    animationSpeed: 0.8,
    captionDepth: 'front',
    position: 'center',
    numberEmphasis: 'auto',
  },
  {
    id: 'cinematic',
    name: 'CINEMATIC',
    description: 'Restrained, refined, very slow entrance. Perfect for storytelling.',
    fontFamily: '"Cormorant Garamond", serif',
    fontWeight: 400,
    fontStyle: 'normal',
    textTransform: 'none',
    baseColor: '#f0f0f0',
    baseSize: 28,
    baseOpacity: 0.8,
    heroColor: '#ffffff',
    heroScale: 1.1,
    heroFontWeight: 600,
    heroFontStyle: 'italic',
    accentColor: '#ffffff',
    alignment: 'center',
    layoutType: 'cinematic',
    letterSpacing: '0.04em',
    lineHeight: 1.4,
    shadow: '0px 2px 20px rgba(0,0,0,0.8)',
    entranceAnimation: 'soft-reveal',
    heroEntranceAnimation: 'focus-in',
    wordActivation: 'none',
    animationSpeed: 1.5,
    captionDepth: 'front',
    position: 'bottom',
    numberEmphasis: 'never',
  },
  {
    id: 'kinetic',
    name: 'KINETIC',
    description: 'Highly energetic per-word animation with strong elastic behavior.',
    fontFamily: '"JetBrains Mono", monospace',
    fontWeight: 800,
    fontStyle: 'normal',
    textTransform: 'uppercase',
    baseColor: '#ffffff',
    baseSize: 42,
    baseOpacity: 1.0,
    heroColor: '#00ffff',
    heroScale: 1.3,
    heroFontWeight: 800,
    heroFontStyle: 'normal',
    accentColor: '#ff00ff',
    alignment: 'center',
    layoutType: 'kinetic',
    letterSpacing: '0',
    lineHeight: 1.1,
    shadow: 'none',
    entranceAnimation: 'glitch',
    heroEntranceAnimation: 'stretch-in',
    wordActivation: 'scale-up',
    animationSpeed: 0.7,
    captionDepth: 'front',
    position: 'center',
    numberEmphasis: 'auto',
  },
  {
    id: 'vertical-stack',
    name: 'VERTICAL STACK',
    description: 'Each word stacked with high scale contrast.',
    fontFamily: '"Geist", sans-serif',
    fontWeight: 800,
    fontStyle: 'normal',
    textTransform: 'uppercase',
    baseColor: '#ffffff',
    baseSize: 36,
    baseOpacity: 0.9,
    heroColor: '#ff00aa',
    heroScale: 1.8,
    heroFontWeight: 900,
    heroFontStyle: 'normal',
    accentColor: '#ffffff',
    alignment: 'center',
    layoutType: 'vertical-stack',
    letterSpacing: '-0.02em',
    lineHeight: 0.9,
    shadow: '0px 4px 12px rgba(0,0,0,0.5)',
    entranceAnimation: 'cascade',
    heroEntranceAnimation: 'pop-in',
    wordActivation: 'none',
    animationSpeed: 1.0,
    captionDepth: 'behind-subject',
    position: 'center',
    numberEmphasis: 'auto',
  },
];

export function getTemplate(id: string): TemplateDefinition {
  return TEMPLATES.find(t => t.id === id) || TEMPLATES[0];
}
