import type { TemplateDefinition } from './types';

export const TEMPLATES: TemplateDefinition[] = [
  // ─── EDITORIAL (default) ──────────────────────────────────────────────────
  // Matches the reference: small red italic supporting words + massive red bold-italic hero
  {
    id: 'editorial',
    name: 'EDITORIAL',
    description: 'Large red bold-italic hero word with small supporting words. Classic editorial typography.',
    fontFamily: '"Playfair Display", serif',
    fontWeight: 400,
    fontStyle: 'italic',
    textTransform: 'none',
    baseColor: '#cc1111',
    baseSize: 28,
    baseOpacity: 0.85,
    heroColor: '#cc1111',
    heroScale: 2.8,
    heroFontFamily: '"Playfair Display", serif',
    heroFontWeight: 700,
    heroFontStyle: 'italic',
    accentColor: '#cc1111',
    alignment: 'center',
    layoutType: 'editorial',
    letterSpacing: '0.01em',
    lineHeight: 1.0,
    shadow: 'none',
    entranceAnimation: 'fade-up',
    wordActivation: 'none',
    animationSpeed: 1.0,
    captionDepth: 'front',
    position: 'center',
  },

  // ─── EDITORIAL DARK ───────────────────────────────────────────────────────
  // Dark bg version: white supporting, red hero
  {
    id: 'editorial-dark',
    name: 'EDITORIAL DARK',
    description: 'White small supporting words, large red hero. For dark video backgrounds.',
    fontFamily: '"Playfair Display", serif',
    fontWeight: 400,
    fontStyle: 'italic',
    textTransform: 'none',
    baseColor: '#ffffff',
    baseSize: 28,
    baseOpacity: 0.85,
    heroColor: '#e02020',
    heroScale: 2.8,
    heroFontFamily: '"Playfair Display", serif',
    heroFontWeight: 700,
    heroFontStyle: 'italic',
    accentColor: '#cccccc',
    alignment: 'center',
    layoutType: 'editorial',
    letterSpacing: '0.01em',
    lineHeight: 1.0,
    shadow: '0px 2px 12px rgba(0,0,0,0.4)',
    entranceAnimation: 'fade-up',
    wordActivation: 'none',
    animationSpeed: 1.0,
    captionDepth: 'front',
    position: 'center',
  },

  // ─── SERIF BLOOM ─────────────────────────────────────────────────────────
  {
    id: 'serif-bloom',
    name: 'SERIF BLOOM',
    description: 'Elegant serif typography with warm tones and editorial composition.',
    fontFamily: '"Playfair Display", serif',
    fontWeight: 600,
    fontStyle: 'italic',
    textTransform: 'none',
    baseColor: '#f2eae1',
    baseSize: 42,
    baseOpacity: 0.8,
    heroColor: '#ffffff',
    heroScale: 1.6,
    heroFontFamily: '"Playfair Display", serif',
    heroFontWeight: 800,
    heroFontStyle: 'italic',
    accentColor: '#d6c5b3',
    alignment: 'center',
    layoutType: 'inline',
    letterSpacing: '0.02em',
    lineHeight: 1.2,
    shadow: '0px 2px 8px rgba(0,0,0,0.4)',
    entranceAnimation: 'fade',
    wordActivation: 'color-fill',
    animationSpeed: 1.0,
    captionDepth: 'front',
    position: 'center',
  },

  // ─── SIGNAL ───────────────────────────────────────────────────────────────
  {
    id: 'signal',
    name: 'SIGNAL',
    description: 'Bold sans-serif, compact word grouping, strong readability.',
    fontFamily: '"Geist", sans-serif',
    fontWeight: 700,
    fontStyle: 'normal',
    textTransform: 'uppercase',
    baseColor: '#ffffff',
    baseSize: 48,
    baseOpacity: 0.9,
    heroColor: '#00ffaa',
    heroScale: 1.2,
    heroFontWeight: 900,
    heroFontStyle: 'normal',
    accentColor: '#a0a0a0',
    alignment: 'center',
    layoutType: 'inline',
    letterSpacing: '-0.02em',
    lineHeight: 1.1,
    shadow: '0px 4px 12px rgba(0,0,0,0.6)',
    entranceAnimation: 'slide-up',
    wordActivation: 'color-fill',
    animationSpeed: 1.0,
    captionDepth: 'front',
    position: 'bottom',
  },

  // ─── CLEAN FOCUS ──────────────────────────────────────────────────────────
  {
    id: 'clean-focus',
    name: 'CLEAN FOCUS',
    description: 'Bold modern sans, minimal composition, single-word emphasis.',
    fontFamily: '"Geist", sans-serif',
    fontWeight: 600,
    fontStyle: 'normal',
    textTransform: 'none',
    baseColor: '#e0e0e0',
    baseSize: 40,
    baseOpacity: 0.7,
    heroColor: '#ffffff',
    heroScale: 1.3,
    heroFontWeight: 800,
    heroFontStyle: 'normal',
    accentColor: '#9b82f3',
    alignment: 'center',
    layoutType: 'inline',
    letterSpacing: '0',
    lineHeight: 1.3,
    shadow: 'none',
    entranceAnimation: 'blur-in',
    wordActivation: 'color-fill',
    animationSpeed: 1.0,
    captionDepth: 'front',
    position: 'bottom',
  },

  // ─── COMIC PUNCH ──────────────────────────────────────────────────────────
  {
    id: 'comic-punch',
    name: 'COMIC PUNCH',
    description: 'Large display typography, uppercase hero words, energetic scale.',
    fontFamily: '"JetBrains Mono", monospace',
    fontWeight: 800,
    fontStyle: 'normal',
    textTransform: 'uppercase',
    baseColor: '#ffffff',
    baseSize: 52,
    baseOpacity: 1,
    heroColor: '#ffcc00',
    heroScale: 1.4,
    heroFontWeight: 800,
    heroFontStyle: 'normal',
    accentColor: '#ffffff',
    alignment: 'center',
    layoutType: 'inline',
    letterSpacing: '0.05em',
    lineHeight: 1.1,
    outline: '3px solid #000000',
    shadow: '4px 4px 0px #000000',
    entranceAnimation: 'bounce',
    wordActivation: 'scale-up',
    animationSpeed: 0.8,
    captionDepth: 'front',
    position: 'center',
  },

  // ─── POSTER ───────────────────────────────────────────────────────────────
  {
    id: 'poster',
    name: 'POSTER',
    description: 'Poster-like layout, very large hero word, asymmetric positioning.',
    fontFamily: '"Geist", sans-serif',
    fontWeight: 800,
    fontStyle: 'normal',
    textTransform: 'uppercase',
    baseColor: '#ffffff',
    baseSize: 32,
    baseOpacity: 0.9,
    heroColor: '#ffffff',
    heroScale: 2.5,
    heroFontWeight: 900,
    heroFontStyle: 'normal',
    accentColor: '#cccccc',
    alignment: 'left',
    layoutType: 'asymmetric',
    letterSpacing: '-0.04em',
    lineHeight: 0.9,
    shadow: '0px 8px 24px rgba(0,0,0,0.5)',
    entranceAnimation: 'reveal',
    wordActivation: 'none',
    animationSpeed: 1.2,
    captionDepth: 'front',
    position: 'center',
  },

  // ─── AMBER STACK ──────────────────────────────────────────────────────────
  {
    id: 'amber-stack',
    name: 'AMBER STACK',
    description: 'Stacked layout, dominant hero word, amber hero, vertical hierarchy.',
    fontFamily: '"Geist", sans-serif',
    fontWeight: 700,
    fontStyle: 'normal',
    textTransform: 'uppercase',
    baseColor: '#ffffff',
    baseSize: 44,
    baseOpacity: 0.9,
    heroColor: '#ff8c00',
    heroScale: 1.6,
    heroFontWeight: 900,
    heroFontStyle: 'normal',
    accentColor: '#ffb77d',
    alignment: 'center',
    layoutType: 'stacked',
    letterSpacing: '0.01em',
    lineHeight: 1.0,
    shadow: '0px 4px 16px rgba(0,0,0,0.8)',
    entranceAnimation: 'slide-up',
    wordActivation: 'color-fill',
    animationSpeed: 1.0,
    captionDepth: 'front',
    position: 'bottom',
  },

  // ─── EDITORIAL FRAME ──────────────────────────────────────────────────────
  {
    id: 'editorial-frame',
    name: 'EDITORIAL FRAME',
    description: 'Large hero word, smaller supporting words, clean negative space.',
    fontFamily: '"Cormorant Garamond", serif',
    fontWeight: 400,
    fontStyle: 'normal',
    textTransform: 'none',
    baseColor: '#ffffff',
    baseSize: 28,
    baseOpacity: 0.7,
    heroColor: '#ffffff',
    heroScale: 2.2,
    heroFontFamily: '"Cormorant Garamond", serif',
    heroFontWeight: 700,
    heroFontStyle: 'italic',
    accentColor: '#a0a0a0',
    alignment: 'left',
    layoutType: 'editorial',
    letterSpacing: '0',
    lineHeight: 1.1,
    shadow: '0px 2px 10px rgba(0,0,0,0.3)',
    entranceAnimation: 'fade',
    wordActivation: 'none',
    animationSpeed: 1.3,
    captionDepth: 'front',
    position: 'bottom-left',
  },

  // ─── PREMIERE ─────────────────────────────────────────────────────────────
  {
    id: 'premiere',
    name: 'PREMIERE',
    description: 'Dramatic serif hero, cinematic composition, red hero treatment.',
    fontFamily: '"EB Garamond", serif',
    fontWeight: 400,
    fontStyle: 'italic',
    textTransform: 'none',
    baseColor: '#ffffff',
    baseSize: 32,
    baseOpacity: 0.85,
    heroColor: '#cc1111',
    heroScale: 2.2,
    heroFontFamily: '"Playfair Display", serif',
    heroFontWeight: 800,
    heroFontStyle: 'italic',
    accentColor: '#e0e0e0',
    alignment: 'center',
    layoutType: 'editorial',
    letterSpacing: '0.02em',
    lineHeight: 1.1,
    shadow: '0px 4px 20px rgba(0,0,0,0.6)',
    entranceAnimation: 'fade-up',
    wordActivation: 'none',
    animationSpeed: 1.2,
    captionDepth: 'front',
    position: 'center',
  },

  // ─── NEW COMPOSITION TEMPLATES ───────────────────────────────────────────
  {
    id: 'editorial-stack',
    name: 'EDITORIAL STACK',
    description: 'Kinetic typography composition stacking small supporting text above/below a massive editorial hero word.',
    fontFamily: '"Geist", sans-serif',
    fontWeight: 500,
    fontStyle: 'normal',
    textTransform: 'uppercase',
    baseColor: '#ffffff',
    baseSize: 32,
    baseOpacity: 0.9,
    heroColor: '#cc1111', // Deep editorial red
    heroScale: 3.5,
    heroFontWeight: 900,
    heroFontStyle: 'normal',
    accentColor: '#cccccc',
    alignment: 'center',
    layoutType: 'editorial-stack',
    letterSpacing: '-0.02em',
    lineHeight: 1.0,
    shadow: '0px 4px 12px rgba(0,0,0,0.6)',
    entranceAnimation: 'rise',
    heroEntranceAnimation: 'punch-in',
    wordActivation: 'none',
    animationSpeed: 1.0,
    captionDepth: 'front',
    position: 'center',
    numberEmphasis: 'auto',
  },
  {
    id: 'hero-interruption',
    name: 'HERO INTERRUPTION',
    description: 'Hero word physically breaks the sentence with generous overlap.',
    fontFamily: '"Geist", sans-serif',
    fontWeight: 600,
    fontStyle: 'normal',
    textTransform: 'uppercase',
    baseColor: '#ffffff',
    baseSize: 32,
    baseOpacity: 0.9,
    heroColor: '#ff0055',
    heroScale: 2.5,
    heroFontWeight: 900,
    heroFontStyle: 'italic',
    accentColor: '#cccccc',
    alignment: 'center',
    layoutType: 'hero-interruption',
    letterSpacing: '-0.02em',
    lineHeight: 1.0,
    shadow: '0px 4px 12px rgba(0,0,0,0.6)',
    entranceAnimation: 'rise',
    heroEntranceAnimation: 'punch-in',
    wordActivation: 'none',
    animationSpeed: 1.0,
    captionDepth: 'front',
    position: 'center',
    numberEmphasis: 'auto',
  },
  {
    id: 'corner-hero-tl',
    name: 'CORNER HERO',
    description: 'Supporting text at the bottom, hero pinned to top-left.',
    fontFamily: '"Geist", sans-serif',
    fontWeight: 500,
    fontStyle: 'normal',
    textTransform: 'none',
    baseColor: '#ffffff',
    baseSize: 36,
    baseOpacity: 0.8,
    heroColor: '#ffffff',
    heroScale: 2.0,
    heroFontWeight: 800,
    heroFontStyle: 'normal',
    accentColor: '#aaaaaa',
    alignment: 'center',
    layoutType: 'corner-hero',
    heroPosition: 'corner-tl',
    letterSpacing: '0',
    lineHeight: 1.2,
    shadow: 'none',
    entranceAnimation: 'fade-up',
    heroEntranceAnimation: 'pop-in',
    wordActivation: 'none',
    animationSpeed: 1.0,
    captionDepth: 'front',
    position: 'bottom',
    numberEmphasis: 'always',
    countUpEnabled: true,
  },
  {
    id: 'split-hero',
    name: 'SPLIT HERO',
    description: 'Words distributed vertically. Excellent for short phrases.',
    fontFamily: '"Playfair Display", serif',
    fontWeight: 700,
    fontStyle: 'italic',
    textTransform: 'none',
    baseColor: '#ffffff',
    baseSize: 42,
    baseOpacity: 1.0,
    heroColor: '#e02020',
    heroScale: 1.5,
    heroFontWeight: 800,
    heroFontStyle: 'italic',
    accentColor: '#ffffff',
    alignment: 'center',
    layoutType: 'split-hero',
    letterSpacing: '0.02em',
    lineHeight: 1.0,
    shadow: '0px 2px 10px rgba(0,0,0,0.5)',
    entranceAnimation: 'stagger',
    wordActivation: 'none',
    animationSpeed: 1.2,
    captionDepth: 'front',
    position: 'center',
    numberEmphasis: 'auto',
  },
  {
    id: 'giant-bg',
    name: 'GIANT WORD',
    description: 'Huge ghosted background word behind the main caption.',
    fontFamily: '"Geist", sans-serif',
    fontWeight: 700,
    fontStyle: 'normal',
    textTransform: 'uppercase',
    baseColor: '#ffffff',
    baseSize: 32,
    baseOpacity: 1.0,
    heroColor: '#ffffff',
    heroScale: 1.5,
    heroFontWeight: 900,
    heroFontStyle: 'normal',
    accentColor: '#cccccc',
    alignment: 'center',
    layoutType: 'giant-bg',
    bgWordOpacity: 0.15,
    bgWordBlur: 4,
    bgWordSize: 180,
    letterSpacing: '-0.02em',
    lineHeight: 1.1,
    shadow: '0px 2px 8px rgba(0,0,0,0.8)',
    entranceAnimation: 'slide-up',
    heroEntranceAnimation: 'fade',
    wordActivation: 'color-fill',
    animationSpeed: 1.0,
    captionDepth: 'front',
    position: 'center',
    numberEmphasis: 'auto',
  },
  {
    id: 'sentence-hero',
    name: 'SENTENCE HERO',
    description: 'Full sentence kept readable with one massive hero word above.',
    fontFamily: '"Geist", sans-serif',
    fontWeight: 500,
    fontStyle: 'normal',
    textTransform: 'none',
    baseColor: '#ffffff',
    baseSize: 32,
    baseOpacity: 0.8,
    heroColor: '#00ffaa',
    heroScale: 2.2,
    heroFontWeight: 900,
    heroFontStyle: 'normal',
    accentColor: '#ffffff',
    alignment: 'center',
    layoutType: 'sentence-hero',
    letterSpacing: '0',
    lineHeight: 1.2,
    shadow: '0px 4px 12px rgba(0,0,0,0.6)',
    entranceAnimation: 'fade-up',
    heroEntranceAnimation: 'elastic-rise',
    wordActivation: 'none',
    animationSpeed: 1.0,
    captionDepth: 'front',
    position: 'bottom',
    numberEmphasis: 'always',
    countUpEnabled: true,
  },
  {
    id: 'hero-micro',
    name: 'HERO + MICRO',
    description: 'Massive hero word with tiny contextual labels.',
    fontFamily: '"Geist", sans-serif',
    fontWeight: 700,
    fontStyle: 'uppercase',
    textTransform: 'uppercase',
    baseColor: '#aaaaaa',
    baseSize: 24,
    baseOpacity: 1.0,
    heroColor: '#ffffff',
    heroScale: 3.5,
    heroFontWeight: 900,
    heroFontStyle: 'normal',
    accentColor: '#ffffff',
    alignment: 'center',
    layoutType: 'hero-micro',
    letterSpacing: '0.05em',
    lineHeight: 1.0,
    shadow: 'none',
    entranceAnimation: 'fade',
    heroEntranceAnimation: 'zoom-in',
    wordActivation: 'none',
    animationSpeed: 1.2,
    captionDepth: 'front',
    position: 'center',
    numberEmphasis: 'always',
    countUpEnabled: true,
  },
  {
    id: 'word-collision',
    name: 'WORD COLLISION',
    description: 'Words enter from opposite directions and collide.',
    fontFamily: '"Geist", sans-serif',
    fontWeight: 900,
    fontStyle: 'normal',
    textTransform: 'uppercase',
    baseColor: '#ffffff',
    baseSize: 48,
    baseOpacity: 1.0,
    heroColor: '#ffcc00',
    heroScale: 1.2,
    heroFontWeight: 900,
    heroFontStyle: 'italic',
    accentColor: '#ffffff',
    alignment: 'center',
    layoutType: 'word-collision',
    letterSpacing: '-0.03em',
    lineHeight: 1.0,
    shadow: '4px 4px 0px rgba(0,0,0,1)',
    entranceAnimation: 'collision-left',
    heroEntranceAnimation: 'collision-right',
    wordActivation: 'none',
    animationSpeed: 0.8,
    captionDepth: 'front',
    position: 'center',
    numberEmphasis: 'auto',
  },
  {
    id: 'cinematic',
    name: 'CINEMATIC',
    description: 'Restrained, refined, very slow entrance. Perfect for storytelling.',
    fontFamily: '"Cormorant Garamond", serif',
    fontWeight: 400,
    fontStyle: 'normal',
    textTransform: 'none',
    baseColor: '#f0f0f0',
    baseSize: 28,
    baseOpacity: 0.8,
    heroColor: '#ffffff',
    heroScale: 1.1,
    heroFontWeight: 600,
    heroFontStyle: 'italic',
    accentColor: '#ffffff',
    alignment: 'center',
    layoutType: 'cinematic',
    letterSpacing: '0.04em',
    lineHeight: 1.4,
    shadow: '0px 2px 20px rgba(0,0,0,0.8)',
    entranceAnimation: 'soft-reveal',
    heroEntranceAnimation: 'focus-in',
    wordActivation: 'none',
    animationSpeed: 1.5,
    captionDepth: 'front',
    position: 'bottom',
    numberEmphasis: 'never',
  },
  {
    id: 'kinetic',
    name: 'KINETIC',
    description: 'Highly energetic per-word animation with strong elastic behavior.',
    fontFamily: '"JetBrains Mono", monospace',
    fontWeight: 800,
    fontStyle: 'normal',
    textTransform: 'uppercase',
    baseColor: '#ffffff',
    baseSize: 42,
    baseOpacity: 1.0,
    heroColor: '#00ffff',
    heroScale: 1.3,
    heroFontWeight: 800,
    heroFontStyle: 'normal',
    accentColor: '#ff00ff',
    alignment: 'center',
    layoutType: 'kinetic',
    letterSpacing: '0',
    lineHeight: 1.1,
    shadow: 'none',
    entranceAnimation: 'glitch',
    heroEntranceAnimation: 'stretch-in',
    wordActivation: 'scale-up',
    animationSpeed: 0.7,
    captionDepth: 'front',
    position: 'center',
    numberEmphasis: 'auto',
  },
  {
    id: 'vertical-stack',
    name: 'VERTICAL STACK',
    description: 'Each word stacked with high scale contrast.',
    fontFamily: '"Geist", sans-serif',
    fontWeight: 800,
    fontStyle: 'normal',
    textTransform: 'uppercase',
    baseColor: '#ffffff',
    baseSize: 36,
    baseOpacity: 0.9,
    heroColor: '#ff00aa',
    heroScale: 1.8,
    heroFontWeight: 900,
    heroFontStyle: 'normal',
    accentColor: '#ffffff',
    alignment: 'center',
    layoutType: 'vertical-stack',
    letterSpacing: '-0.02em',
    lineHeight: 0.9,
    shadow: '0px 4px 12px rgba(0,0,0,0.5)',
    entranceAnimation: 'cascade',
    heroEntranceAnimation: 'pop-in',
    wordActivation: 'none',
    animationSpeed: 1.0,
    captionDepth: 'front',
    position: 'center',
    numberEmphasis: 'auto',
  },
  {
    id: 'scribble-highlight',
    name: 'SCRIBBLE HIGHLIGHT',
    description: 'Dynamic handwritten typography with animated scribble underlays for emphasized words.',
    fontFamily: '"Geist", sans-serif',
    fontWeight: 600,
    fontStyle: 'normal',
    textTransform: 'uppercase',
    baseColor: '#ffffff',
    baseSize: 36,
    baseOpacity: 1.0,
    heroColor: '#111111',
    heroScale: 1.4,
    heroFontFamily: '"Caveat", cursive',
    heroFontWeight: 700,
    heroFontStyle: 'normal',
    accentColor: '#ffffff',
    alignment: 'center',
    layoutType: 'scribble-highlight',
    letterSpacing: '0.02em',
    lineHeight: 1.2,
    shadow: '0px 2px 8px rgba(0,0,0,0.5)',
    entranceAnimation: 'pop-in',
    heroEntranceAnimation: 'pop-in',
    wordActivation: 'highlight',
    animationSpeed: 1.0,
    captionDepth: 'front',
    position: 'center',
    numberEmphasis: 'auto',
    scribbleColor: '#FFD700',
    scribbleType: 'underline',
  },
  {
    id: 'layered-editorial',
    name: 'LAYERED EDITORIAL',
    description: 'Massive serif hero text placed behind the subject, with small sans-serif supporting text overlapping in front.',
    fontFamily: '"Geist", sans-serif',
    fontWeight: 500,
    fontStyle: 'normal',
    textTransform: 'none',
    baseColor: '#ffffff',
    baseSize: 32,
    baseOpacity: 0.9,
    heroColor: '#ff2255',
    heroScale: 2.8,
    heroFontFamily: '"Playfair Display", serif',
    heroFontWeight: 800,
    heroFontStyle: 'italic',
    accentColor: '#cccccc',
    alignment: 'center',
    layoutType: 'layered-editorial',
    letterSpacing: '0.01em',
    lineHeight: 1.1,
    shadow: '0px 4px 16px rgba(0,0,0,0.8)',
    entranceAnimation: 'fade-up',
    heroEntranceAnimation: 'fade-up',
    wordActivation: 'none',
    animationSpeed: 1.2,
    captionDepth: 'mixed',
    position: 'center',
    numberEmphasis: 'always',
  },
  {
    id: 'continuous-scroll',
    name: 'CONTINUOUS SCROLL',
    description: 'Text continuously flows through the frame with soft gradient masking at the edges.',
    fontFamily: '"Geist", sans-serif',
    fontWeight: 700,
    fontStyle: 'normal',
    textTransform: 'uppercase',
    baseColor: '#ffffff',
    baseSize: 42,
    baseOpacity: 0.8,
    heroColor: '#00e5ff',
    heroScale: 1.2,
    heroFontFamily: '"Geist", sans-serif',
    heroFontWeight: 900,
    heroFontStyle: 'normal',
    accentColor: '#ffffff',
    alignment: 'center',
    layoutType: 'continuous-scroll',
    letterSpacing: '0.02em',
    lineHeight: 1.3,
    shadow: 'none',
    entranceAnimation: 'none',
    heroEntranceAnimation: 'none',
    wordActivation: 'color-fill',
    animationSpeed: 1.0,
    captionDepth: 'front',
    position: 'center',
    numberEmphasis: 'auto',
    continuousScroll: {
      direction: 'up',
      speedMultiplier: 1.0,
      maskGradient: 'linear-gradient(to bottom, transparent 0%, black 15%, black 85%, transparent 100%)',
    },
  }
];

// ─────────────────────────────────────────────────────────────────────────────
// MOGRT-DERIVED TEMPLATES (source-verified from definition.json)
// These are appended after the base templates array for incremental rollout.
// ─────────────────────────────────────────────────────────────────────────────
TEMPLATES.push(

  // 1. SLIDE COLLIDE
  // Source: Premium Text Animations/Slide Collide.mogrt
  // Effects: ADBE Geometry2, ADBE Glo2, ADBE Ramp, CC Light Sweep
  // Fonts: Coolvetica-Regular (word1), Vivaldii (word2)
  // Colors: GradientStart #FF9600 (1,0.588,0,1) → GradientEnd #2B1800 (0.168,0.094,0,1)
  // Animation: two text layers enter from opposite sides and collide at center
  // Text level: per-word — odd words from left, even words from right
  // Duration: ~3.8s (23 frames @ 6fps), easeOutCubic
  {
    id: 'slide-collide',
    name: 'SLIDE COLLIDE',
    description: 'Words collide from opposite sides. Odd words slide from left, even from right. Orange gradient with glow.',
    category: 'MOGRT',
    fontFamily: '"Geist", sans-serif',
    fontWeight: 800,
    fontStyle: 'normal',
    textTransform: 'uppercase',
    baseColor: '#FF9600',
    baseSize: 52,
    baseOpacity: 1,
    heroColor: '#FFCC44',
    heroScale: 1.3,
    heroFontWeight: 900,
    heroFontStyle: 'normal',
    accentColor: '#FF9600',
    alignment: 'center',
    layoutType: 'inline',
    letterSpacing: '-0.01em',
    lineHeight: 1.1,
    shadow: '0px 0px 20px rgba(255,150,0,0.6)',
    entranceAnimation: 'collision-left',
    heroEntranceAnimation: 'collision-right',
    wordActivation: 'scale-up',
    animationSpeed: 0.85,
    captionDepth: 'front',
    position: 'center',
  },

  // 2. SPINNING BUTTER
  // Source: Premium Text Animations/Spinning Butter.mogrt
  // Effects: ADBE Geometry2, ADBE Glo2, ADBE Ramp, CC Light Sweep
  // Fonts: Coolvetica-Regular
  // Colors: Word1 white→black gradient; Word2 purple(0.612,0,0.612,1)→black gradient
  // Animation: per-word spin-in (rotateZ 180°→0°) + scale 0.4→1 easeOutBack + blur fade
  // Text level: per-word
  // Duration: ~3.8s (23/6fps), stagger 0.08s per word
  {
    id: 'spinning-butter',
    name: 'SPINNING BUTTER',
    description: 'Each word spins in from 180° with overshoot scale. White/purple gradient with glow.',
    category: 'MOGRT',
    fontFamily: '"Geist", sans-serif',
    fontWeight: 800,
    fontStyle: 'normal',
    textTransform: 'uppercase',
    baseColor: '#ffffff',
    baseSize: 52,
    baseOpacity: 1,
    heroColor: '#CC44FF',
    heroScale: 1.4,
    heroFontWeight: 900,
    heroFontStyle: 'normal',
    accentColor: '#ffffff',
    alignment: 'center',
    layoutType: 'inline',
    letterSpacing: '0.02em',
    lineHeight: 1.15,
    shadow: '0px 0px 24px rgba(200,100,255,0.5)',
    entranceAnimation: 'spin-in',
    heroEntranceAnimation: 'spin-in',
    wordActivation: 'scale-up',
    animationSpeed: 0.9,
    captionDepth: 'front',
    position: 'center',
  },

  // 3. ZOOM IN
  // Source: Premium Text Animations/Zoom In.mogrt
  // Effects: ADBE Glo2, ADBE Ramp, CC Light Sweep
  // Fonts: Poppins-ExtraBold, 211pt
  // Colors: Cyan (0,0.824,1,1) → Deep Blue (0,0.295,0.784,1) gradient
  // Animation: scale from 0→1 with easeOutBack overshoot, glow on entry
  // Text level: per-word, stagger 0.07s
  // Duration: ~3.6s (9009/2500fps)
  {
    id: 'zoom-in-mogrt',
    name: 'ZOOM IN',
    description: 'Words zoom in from zero scale with overshoot. Cyan to blue gradient with glow.',
    category: 'MOGRT',
    fontFamily: '"Geist", sans-serif',
    fontWeight: 900,
    fontStyle: 'normal',
    textTransform: 'uppercase',
    baseColor: '#00D2FF',
    baseSize: 54,
    baseOpacity: 1,
    heroColor: '#4B9FFF',
    heroScale: 1.35,
    heroFontWeight: 900,
    heroFontStyle: 'normal',
    accentColor: '#00D2FF',
    alignment: 'center',
    layoutType: 'inline',
    letterSpacing: '-0.02em',
    lineHeight: 1.1,
    shadow: '0px 0px 28px rgba(0,210,255,0.55)',
    entranceAnimation: 'zoom-in',
    heroEntranceAnimation: 'zoom-in',
    wordActivation: 'scale-up',
    animationSpeed: 0.8,
    captionDepth: 'front',
    position: 'center',
  },

  // 4. SMOOTH SLIDE LEFT
  // Source: Expensive_Looking_Text_Presets/Smooth_Slide_Left.mogrt
  // Effects: ADBE Drop Shadow, ADBE Glo2, ADBE Ramp, ADBE Slider Control
  // Fonts: Roboto-Bold, 234.5pt
  // Colors: GradientStart #C600FF (0.776,0,1,1) → GradientEnd #6B0089 (0.42,0,0.541,1)
  // Animation: whole segment slides in from right (X=+fullWidth → 0), opacity 0→100
  // Text level: per-segment (whole segment moves together)
  // Duration: 1.3s (from Animation Duration control), easeOutCubic
  // Position: 1080×1920 (9:16 canvas), center
  {
    id: 'smooth-slide-left',
    name: 'SMOOTH SLIDE LEFT',
    description: 'Segment slides in from right with glow. Purple gradient. 1.3s ease. Whole segment enters together.',
    category: 'MOGRT',
    fontFamily: '"Geist", sans-serif',
    fontWeight: 700,
    fontStyle: 'normal',
    textTransform: 'none',
    baseColor: '#C600FF',
    baseSize: 48,
    baseOpacity: 1,
    heroColor: '#E055FF',
    heroScale: 1.2,
    heroFontWeight: 800,
    heroFontStyle: 'normal',
    accentColor: '#C600FF',
    alignment: 'center',
    layoutType: 'inline',
    letterSpacing: '0',
    lineHeight: 1.2,
    shadow: '0px 4px 16px rgba(0,0,0,0.5)',
    entranceAnimation: 'slide-from-right',
    heroEntranceAnimation: 'slide-from-right',
    animationLevel: 'segment',
    wordActivation: 'color-fill',
    animationSpeed: 1.3,
    captionDepth: 'front',
    position: 'center',
  },

  // 5. SLIDING BOTTOM TO UP
  // Source: Expensive_Looking_Text_Presets/Sliding_Bottom_To_Up.mogrt
  // Effects: ADBE Drop Shadow, ADBE Glo2, ADBE Ramp, ADBE Slider Control
  // Fonts: AppleGaramond-BoldItalic, 404pt
  // Colors: Same purple gradient as Smooth Slide Left
  // Animation: whole segment slides from Y=below-frame → final Y, opacity 0→100
  // Text level: per-segment (whole segment moves together as a block)
  // Duration: 1.0s, easeOutCubic
  {
    id: 'sliding-bottom-to-up',
    name: 'SLIDING BOTTOM TO UP',
    description: 'Segment slides up from below frame. Purple gradient with glow and drop shadow. 1.0s ease.',
    category: 'MOGRT',
    fontFamily: '"Playfair Display", serif',
    fontWeight: 700,
    fontStyle: 'italic',
    textTransform: 'none',
    baseColor: '#C600FF',
    baseSize: 50,
    baseOpacity: 1,
    heroColor: '#E055FF',
    heroScale: 1.2,
    heroFontWeight: 800,
    heroFontStyle: 'italic',
    accentColor: '#C600FF',
    alignment: 'center',
    layoutType: 'inline',
    letterSpacing: '0.01em',
    lineHeight: 1.2,
    shadow: '0px 6px 20px rgba(0,0,0,0.6)',
    entranceAnimation: 'slide-from-bottom',
    heroEntranceAnimation: 'slide-from-bottom',
    animationLevel: 'segment',
    wordActivation: 'color-fill',
    animationSpeed: 1.0,
    captionDepth: 'front',
    position: 'bottom',
  },

  // 6. SLIDING RIGHT TO LEFT
  // Source: Expensive_Looking_Text_Presets/Sliding_Right_To_Left.mogrt
  // Effects: ADBE Drop Shadow, ADBE Glo2, ADBE Ramp, ADBE Slider Control, ADBE Tint
  // Fonts: AppleGaramond-BoldItalic, 404pt
  // Colors: Same purple gradient — ADBE Tint adds a colorize pass over the text
  // Animation: whole segment enters from far right (X=+wide → final X)
  // The additional ADBE Tint creates a two-tone effect on the text
  // Text level: per-segment
  // Duration: 1.0s, easeOutCubic
  {
    id: 'sliding-right-to-left',
    name: 'SLIDING RIGHT TO LEFT',
    description: 'Segment sweeps in from far right. Tinted purple gradient with heavy glow. 1.0s ease.',
    category: 'MOGRT',
    fontFamily: '"Playfair Display", serif',
    fontWeight: 700,
    fontStyle: 'italic',
    textTransform: 'none',
    baseColor: '#9B00FF',
    baseSize: 50,
    baseOpacity: 1,
    heroColor: '#C844FF',
    heroScale: 1.2,
    heroFontWeight: 800,
    heroFontStyle: 'italic',
    accentColor: '#9B00FF',
    alignment: 'center',
    layoutType: 'inline',
    letterSpacing: '0.01em',
    lineHeight: 1.2,
    shadow: '0px 6px 24px rgba(155,0,255,0.45)',
    entranceAnimation: 'slide-right-to-left',
    heroEntranceAnimation: 'slide-right-to-left',
    animationLevel: 'segment',
    wordActivation: 'color-fill',
    animationSpeed: 1.0,
    captionDepth: 'front',
    position: 'center',
  },
  // ── NEW CKB SLIDE PRESETS ─────────────────────────────────────────
  {
    id: 'slide-down-ckb',
    name: 'SLIDE DOWN BY CKB',
    description: 'Dynamic caption sliding down from the top. High-energy drop-in.',
    category: 'MOGRT',
    fontFamily: '"Geist", sans-serif',
    fontWeight: 800,
    fontStyle: 'normal',
    textTransform: 'uppercase',
    baseColor: '#ffffff',
    baseSize: 48,
    baseOpacity: 1,
    heroColor: '#FFFF00',
    heroScale: 1.2,
    heroFontWeight: 900,
    heroFontStyle: 'normal',
    accentColor: '#ffffff',
    alignment: 'center',
    layoutType: 'inline',
    letterSpacing: '0',
    lineHeight: 1.1,
    shadow: '0px 4px 16px rgba(0,0,0,0.8)',
    entranceAnimation: 'slide-from-top',
    heroEntranceAnimation: 'slide-from-top',
    animationLevel: 'segment',
    wordActivation: 'color-fill',
    animationSpeed: 1.0,
    captionDepth: 'front',
    position: 'center',
  },
  {
    id: 'slide-left-ckb',
    name: 'SLIDE LEFT BY CKB',
    description: 'Dynamic caption sliding left (from right). Fast, snappy entrance.',
    category: 'MOGRT',
    fontFamily: '"Geist", sans-serif',
    fontWeight: 800,
    fontStyle: 'normal',
    textTransform: 'uppercase',
    baseColor: '#ffffff',
    baseSize: 48,
    baseOpacity: 1,
    heroColor: '#00FFAA',
    heroScale: 1.2,
    heroFontWeight: 900,
    heroFontStyle: 'normal',
    accentColor: '#ffffff',
    alignment: 'center',
    layoutType: 'inline',
    letterSpacing: '0',
    lineHeight: 1.1,
    shadow: '0px 4px 16px rgba(0,0,0,0.8)',
    entranceAnimation: 'slide-from-right',
    heroEntranceAnimation: 'slide-from-right',
    animationLevel: 'segment',
    wordActivation: 'color-fill',
    animationSpeed: 1.0,
    captionDepth: 'front',
    position: 'center',
  },
  {
    id: 'slide-right-ckb',
    name: 'SLIDE RIGHT BY CKB',
    description: 'Dynamic caption sliding right (from left). Bold impact.',
    category: 'MOGRT',
    fontFamily: '"Geist", sans-serif',
    fontWeight: 800,
    fontStyle: 'normal',
    textTransform: 'uppercase',
    baseColor: '#ffffff',
    baseSize: 48,
    baseOpacity: 1,
    heroColor: '#FF0055',
    heroScale: 1.2,
    heroFontWeight: 900,
    heroFontStyle: 'normal',
    accentColor: '#ffffff',
    alignment: 'center',
    layoutType: 'inline',
    letterSpacing: '0',
    lineHeight: 1.1,
    shadow: '0px 4px 16px rgba(0,0,0,0.8)',
    entranceAnimation: 'slide-from-left',
    heroEntranceAnimation: 'slide-from-left',
    animationLevel: 'segment',
    wordActivation: 'color-fill',
    animationSpeed: 1.0,
    captionDepth: 'front',
    position: 'center',
  },
  {
    id: 'slide-up-ckb',
    name: 'SLIDE UP BY CKB',
    description: 'Dynamic caption rising from the bottom. Clean pop-up.',
    category: 'MOGRT',
    fontFamily: '"Geist", sans-serif',
    fontWeight: 800,
    fontStyle: 'normal',
    textTransform: 'uppercase',
    baseColor: '#ffffff',
    baseSize: 48,
    baseOpacity: 1,
    heroColor: '#00AAFF',
    heroScale: 1.2,
    heroFontWeight: 900,
    heroFontStyle: 'normal',
    accentColor: '#ffffff',
    alignment: 'center',
    layoutType: 'inline',
    letterSpacing: '0',
    lineHeight: 1.1,
    shadow: '0px 4px 16px rgba(0,0,0,0.8)',
    entranceAnimation: 'slide-from-bottom',
    heroEntranceAnimation: 'slide-from-bottom',
    animationLevel: 'segment',
    wordActivation: 'color-fill',
    animationSpeed: 1.0,
    captionDepth: 'front',
    position: 'center',
  },
  // ── NEW PREMIUM / EXPENSIVE PRESETS ───────────────────────────────
  {
    id: 'reels-text-default',
    name: 'REELS TEXT DEFAULT',
    description: 'Standard Instagram/TikTok clean pop-in with scale up activation.',
    category: 'MOGRT',
    fontFamily: '"Geist", sans-serif',
    fontWeight: 700,
    fontStyle: 'normal',
    textTransform: 'uppercase',
    baseColor: '#ffffff',
    baseSize: 44,
    baseOpacity: 1,
    heroColor: '#FFE600',
    heroScale: 1.25,
    heroFontWeight: 800,
    heroFontStyle: 'normal',
    accentColor: '#ffffff',
    alignment: 'center',
    layoutType: 'inline',
    letterSpacing: '-0.02em',
    lineHeight: 1.15,
    shadow: '0px 2px 8px rgba(0,0,0,0.5)',
    entranceAnimation: 'pop-in',
    heroEntranceAnimation: 'pop-in',
    animationLevel: 'word',
    wordActivation: 'scale-up',
    animationSpeed: 1.0,
    captionDepth: 'front',
    position: 'center',
  },
  {
    id: 'butter-up',
    name: 'BUTTER UP',
    description: 'Smooth buttery spring-up animation. Satisfying elastic ease.',
    category: 'MOGRT',
    fontFamily: '"Playfair Display", serif',
    fontWeight: 700,
    fontStyle: 'italic',
    textTransform: 'none',
    baseColor: '#FFF2CC',
    baseSize: 46,
    baseOpacity: 0.9,
    heroColor: '#FFB800',
    heroScale: 1.3,
    heroFontWeight: 800,
    heroFontStyle: 'italic',
    accentColor: '#FFE066',
    alignment: 'center',
    layoutType: 'inline',
    letterSpacing: '0',
    lineHeight: 1.2,
    shadow: '0px 8px 30px rgba(0,0,0,0.6)',
    entranceAnimation: 'spring-up',
    heroEntranceAnimation: 'spring-up',
    animationLevel: 'word',
    wordActivation: 'color-fill',
    animationSpeed: 1.2,
    captionDepth: 'front',
    position: 'center',
  },
  {
    id: 'coovetica-waving',
    name: 'COOVETICA WAVING',
    description: 'Playful wavy staggered reveal, bouncing along.',
    category: 'MOGRT',
    fontFamily: '"Geist", sans-serif',
    fontWeight: 800,
    fontStyle: 'normal',
    textTransform: 'uppercase',
    baseColor: '#ffffff',
    baseSize: 50,
    baseOpacity: 1,
    heroColor: '#00F0FF',
    heroScale: 1.2,
    heroFontWeight: 900,
    heroFontStyle: 'normal',
    accentColor: '#00F0FF',
    alignment: 'center',
    layoutType: 'inline',
    letterSpacing: '0.02em',
    lineHeight: 1.1,
    shadow: '0px 4px 12px rgba(0,0,0,0.5)',
    entranceAnimation: 'cascade',
    heroEntranceAnimation: 'cascade',
    animationLevel: 'word',
    wordActivation: 'scale-up',
    animationSpeed: 0.8,
    captionDepth: 'front',
    position: 'center',
  },
  {
    id: 'cracked',
    name: 'CRACKED',
    description: 'Aggressive glitchy entrance for high-intensity videos.',
    category: 'MOGRT',
    fontFamily: '"Geist", sans-serif',
    fontWeight: 900,
    fontStyle: 'normal',
    textTransform: 'uppercase',
    baseColor: '#ffffff',
    baseSize: 52,
    baseOpacity: 0.9,
    heroColor: '#FF0044',
    heroScale: 1.4,
    heroFontWeight: 900,
    heroFontStyle: 'normal',
    accentColor: '#ffffff',
    alignment: 'center',
    layoutType: 'inline',
    letterSpacing: '-0.02em',
    lineHeight: 1.1,
    shadow: 'none',
    entranceAnimation: 'glitch',
    heroEntranceAnimation: 'glitch',
    animationLevel: 'word',
    wordActivation: 'none',
    animationSpeed: 0.6,
    captionDepth: 'front',
    position: 'center',
  },
  {
    id: 'ocean-waves',
    name: 'OCEAN WAVES',
    description: 'Smooth, deep blue cascading reveal.',
    category: 'MOGRT',
    fontFamily: '"Playfair Display", serif',
    fontWeight: 600,
    fontStyle: 'italic',
    textTransform: 'none',
    baseColor: '#E6F7FF',
    baseSize: 42,
    baseOpacity: 0.85,
    heroColor: '#0088FF',
    heroScale: 1.3,
    heroFontWeight: 800,
    heroFontStyle: 'italic',
    accentColor: '#66CCFF',
    alignment: 'center',
    layoutType: 'inline',
    letterSpacing: '0.01em',
    lineHeight: 1.25,
    shadow: '0px 2px 10px rgba(0,50,150,0.4)',
    entranceAnimation: 'cascade',
    heroEntranceAnimation: 'cascade',
    animationLevel: 'word',
    wordActivation: 'color-fill',
    animationSpeed: 1.5,
    captionDepth: 'front',
    position: 'center',
  },
  {
    id: 'rock-solidance',
    name: 'ROCK SOLIDANCE',
    description: 'Heavy, abrupt punch-in impact.',
    category: 'MOGRT',
    fontFamily: '"Geist", sans-serif',
    fontWeight: 900,
    fontStyle: 'normal',
    textTransform: 'uppercase',
    baseColor: '#ffffff',
    baseSize: 54,
    baseOpacity: 1,
    heroColor: '#FF3300',
    heroScale: 1.2,
    heroFontWeight: 900,
    heroFontStyle: 'normal',
    accentColor: '#ffffff',
    alignment: 'center',
    layoutType: 'inline',
    letterSpacing: '-0.04em',
    lineHeight: 1.0,
    shadow: '0px 5px 0px rgba(0,0,0,1)',
    entranceAnimation: 'punch-in',
    heroEntranceAnimation: 'punch-in',
    animationLevel: 'word',
    wordActivation: 'scale-up',
    animationSpeed: 0.7,
    captionDepth: 'front',
    position: 'center',
  },
  {
    id: 'santhosham',
    name: 'SANTHOSHAM',
    description: 'Elegant, gentle fade up. Simple and clean.',
    category: 'MOGRT',
    fontFamily: '"Geist", sans-serif',
    fontWeight: 500,
    fontStyle: 'normal',
    textTransform: 'none',
    baseColor: '#ffffff',
    baseSize: 40,
    baseOpacity: 0.9,
    heroColor: '#FFE066',
    heroScale: 1.1,
    heroFontWeight: 600,
    heroFontStyle: 'normal',
    accentColor: '#ffffff',
    alignment: 'center',
    layoutType: 'inline',
    letterSpacing: '0',
    lineHeight: 1.3,
    shadow: '0px 2px 4px rgba(0,0,0,0.6)',
    entranceAnimation: 'fade-up',
    heroEntranceAnimation: 'fade-up',
    animationLevel: 'word',
    wordActivation: 'color-fill',
    animationSpeed: 1.0,
    captionDepth: 'front',
    position: 'center',
  }
);

// ─────────────────────────────────────────────────────────────────────────────
// DYNAMIC PREMIUM TEMPLATES (sourced from reference video analysis)
// Reference videos: C:\Captions AI\caption-app\caption-app\new anim\*.mp4
// ─────────────────────────────────────────────────────────────────────────────
TEMPLATES.push(

  // 1. SERIF + SANS SERIF
  // Reference: serif-sans-serif-text_350p.mp4
  // Visual: Clean white sans-serif supporting words + large italic green script hero word.
  // Position: Bottom-left. Word grouping: 3-4 base + 1 hero. Depth: front.
  {
    id: 'serif-sans-serif',
    name: 'SERIF + SANS SERIF',
    description: 'Editorial contrast: small white sans-serif supporting words + large italic script hero word in vivid green.',
    category: 'Dynamic',
    fontFamily: '"Geist", sans-serif',
    fontWeight: 400,
    fontStyle: 'normal',
    textTransform: 'none',
    baseColor: '#ffffff',
    baseSize: 26,
    baseOpacity: 0.9,
    heroColor: '#7AC943',
    heroScale: 2.3,
    heroFontFamily: '"Playfair Display", serif',
    heroFontWeight: 700,
    heroFontStyle: 'italic',
    accentColor: '#a8d87a',
    alignment: 'left',
    layoutType: 'editorial',
    letterSpacing: '0.01em',
    lineHeight: 1.2,
    shadow: '0px 2px 10px rgba(0,0,0,0.5)',
    entranceAnimation: 'fade-up',
    heroEntranceAnimation: 'word-rise',
    animationLevel: 'word',
    wordActivation: 'none',
    animationSpeed: 1.0,
    captionDepth: 'front',
    position: 'bottom-left',
  },

  // 2. SUBTITLE HIGHLIGHT
  // Reference: subtitle-highlight_350p.mp4
  // Visual: Clean bottom-center subtitles. Active spoken word highlighted with
  // a golden-yellow background pill. No size change. Smooth color transition.
  {
    id: 'subtitle-highlight',
    name: 'SUBTITLE HIGHLIGHT',
    description: 'Clean subtitle-style captions. Active word highlighted with a golden-yellow pill background.',
    category: 'Dynamic',
    fontFamily: '"Geist", sans-serif',
    fontWeight: 500,
    fontStyle: 'normal',
    textTransform: 'none',
    baseColor: '#ffffff',
    baseSize: 36,
    baseOpacity: 1.0,
    heroColor: '#1a1a1a',
    heroScale: 1.0,
    heroFontWeight: 600,
    heroFontStyle: 'normal',
    accentColor: '#F5D020',
    alignment: 'center',
    layoutType: 'subtitle-highlight',
    letterSpacing: '0.005em',
    lineHeight: 1.3,
    shadow: '0px 2px 8px rgba(0,0,0,0.6)',
    entranceAnimation: 'fade',
    animationLevel: 'segment',
    wordActivation: 'highlight',
    highlightColor: '#F5D020',
    highlightPadX: 12,
    highlightPadY: 4,
    highlightRadius: 6,
    animationSpeed: 1.0,
    captionDepth: 'front',
    position: 'bottom',
  },

  // 3. SERIF ITALIC TEXT BEHIND
  // Reference: serif-italic-text-behind_350p.mp4
  // Visual: Very large bold red serif uppercase hero word rendered BEHIND the subject.
  // Occupies upper frame. Word per segment. Real depth compositing via segmentation.
  {
    id: 'serif-italic-behind',
    name: 'SERIF ITALIC BEHIND',
    description: 'Enormous bold red serif word sits behind the subject person. Real depth compositing.',
    category: 'Dynamic',
    fontFamily: '"Playfair Display", serif',
    fontWeight: 400,
    fontStyle: 'normal',
    textTransform: 'none',
    baseColor: '#ffffff',
    baseSize: 24,
    baseOpacity: 0.8,
    heroColor: '#CC1111',
    heroScale: 5.5,
    heroFontFamily: '"Playfair Display", serif',
    heroFontWeight: 800,
    heroFontStyle: 'italic',
    accentColor: '#dd4444',
    alignment: 'center',
    layoutType: 'bold-behind',
    letterSpacing: '-0.02em',
    lineHeight: 0.9,
    shadow: '2px 4px 16px rgba(0,0,0,0.8)',
    entranceAnimation: 'fade',
    heroEntranceAnimation: 'scale-fade',
    animationLevel: 'segment',
    wordActivation: 'none',
    animationSpeed: 1.2,
    captionDepth: 'behind-subject',
    position: 'top',
  },

  // 4. MULTI POSITION TEXT — PLAIN
  // Reference: multi-position-text-plain_350p.mp4
  // Visual: Caption groups move to different safe-zone positions each segment.
  // White only. Supporting words + larger hero. Deterministic position cycling.
  {
    id: 'multi-position-plain',
    name: 'MULTI POSITION — PLAIN',
    description: 'Caption groups cycle through screen positions. White typography only. Stacked word layout.',
    category: 'Dynamic',
    fontFamily: '"Geist", sans-serif',
    fontWeight: 400,
    fontStyle: 'normal',
    textTransform: 'none',
    baseColor: '#ffffff',
    baseSize: 28,
    baseOpacity: 0.9,
    heroColor: '#ffffff',
    heroScale: 1.9,
    heroFontFamily: '"Playfair Display", serif',
    heroFontWeight: 700,
    heroFontStyle: 'italic',
    accentColor: '#dddddd',
    alignment: 'left',
    layoutType: 'multi-position',
    letterSpacing: '0',
    lineHeight: 1.2,
    shadow: '0px 2px 12px rgba(0,0,0,0.7)',
    entranceAnimation: 'scale-fade',
    heroEntranceAnimation: 'scale-fade',
    animationLevel: 'segment',
    wordActivation: 'none',
    animationSpeed: 1.0,
    captionDepth: 'front',
    position: 'top-left',
  },

  // 5. MULTI POSITION TEXT — COLOR
  // Reference: multi-position-text-color_350p.mp4
  // Visual: Same positional cycling as PLAIN, but hero/emphasis word is golden-amber.
  {
    id: 'multi-position-color',
    name: 'MULTI POSITION — COLOR',
    description: 'Cycling screen positions with golden-amber emphasis word. Supporting text white.',
    category: 'Dynamic',
    fontFamily: '"Geist", sans-serif',
    fontWeight: 400,
    fontStyle: 'normal',
    textTransform: 'none',
    baseColor: '#ffffff',
    baseSize: 28,
    baseOpacity: 0.9,
    heroColor: '#F5A623',
    heroScale: 1.9,
    heroFontFamily: '"Playfair Display", serif',
    heroFontWeight: 700,
    heroFontStyle: 'italic',
    accentColor: '#F5C76A',
    alignment: 'left',
    layoutType: 'multi-position',
    letterSpacing: '0',
    lineHeight: 1.2,
    shadow: '0px 2px 12px rgba(0,0,0,0.7)',
    entranceAnimation: 'scale-fade',
    heroEntranceAnimation: 'scale-fade',
    animationLevel: 'segment',
    wordActivation: 'none',
    animationSpeed: 1.0,
    captionDepth: 'front',
    position: 'top-left',
  },

  // 6. DIFFERENCE TEXT
  // Reference: difference-text_350p.mp4
  // Visual: Small supporting words above + very large hero word below. ~3x size ratio.
  // Strong editorial hierarchy. Top-center area. Clean white-on-dark composition.
  {
    id: 'difference-text',
    name: 'DIFFERENCE TEXT',
    description: 'Strong typographic contrast: small supporting text above and massive hero word below.',
    category: 'Dynamic',
    fontFamily: '"Geist", sans-serif',
    fontWeight: 400,
    fontStyle: 'normal',
    textTransform: 'none',
    baseColor: '#ffffff',
    baseSize: 24,
    baseOpacity: 0.85,
    heroColor: '#ffffff',
    heroScale: 3.2,
    heroFontFamily: '"Geist", sans-serif',
    heroFontWeight: 800,
    heroFontStyle: 'normal',
    accentColor: '#d0d0d0',
    alignment: 'center',
    layoutType: 'difference-text',
    letterSpacing: '0',
    lineHeight: 1.1,
    shadow: '0px 2px 12px rgba(0,0,0,0.6)',
    entranceAnimation: 'fade-up',
    heroEntranceAnimation: 'slide-up',
    animationLevel: 'word',
    wordActivation: 'none',
    animationSpeed: 1.0,
    captionDepth: 'front',
    position: 'top',
  },

  // 7. BOLD TEXT BEHIND
  // Reference: bold-text-behind_350p.mp4
  // Visual: Ultra-bold yellow uppercase word behind the subject. Enormous scale.
  // Real depth compositing. Safe fallback to foreground if segmentation unavailable.
  {
    id: 'bold-text-behind',
    name: 'BOLD TEXT BEHIND',
    description: 'Oversized bold yellow uppercase word placed behind the subject via depth compositing.',
    category: 'Dynamic',
    fontFamily: '"Geist", sans-serif',
    fontWeight: 900,
    fontStyle: 'normal',
    textTransform: 'uppercase',
    baseColor: '#ffffff',
    baseSize: 24,
    baseOpacity: 0.85,
    heroColor: '#FFE600',
    heroScale: 5.5,
    heroFontFamily: '"Geist", sans-serif',
    heroFontWeight: 900,
    heroFontStyle: 'normal',
    accentColor: '#FFE600',
    alignment: 'center',
    layoutType: 'bold-behind',
    letterSpacing: '-0.04em',
    lineHeight: 0.85,
    shadow: '2px 4px 16px rgba(0,0,0,0.85)',
    entranceAnimation: 'fade',
    heroEntranceAnimation: 'scale-fade',
    animationLevel: 'segment',
    wordActivation: 'none',
    animationSpeed: 1.2,
    captionDepth: 'behind-subject',
    position: 'top',
  },


  // --- IMPORTED VIRAL TEMPLATES ---

  // WORD BY WORD (from caption-templates)
  {
    id: 'word-by-word',
    name: 'Word by Word',
    description: "The classic viral caption: white words with a black stroke, the active word flashes yellow and pops.",
    category: 'Viral',
    fontFamily: "'Inter', sans-serif",
    fontWeight: 800,
    fontStyle: 'normal',
    textTransform: 'uppercase',
    baseColor: '#ffffff',
    baseSize: 140,
    baseOpacity: 1,
    heroColor: '#FFE500',
    heroScale: 1.18,
    heroFontWeight: 800,
    heroFontStyle: 'normal',
    accentColor: '#FFE500',
    alignment: 'center',
    layoutType: 'inline',
    letterSpacing: '0.01em',
    lineHeight: 1.25,
    shadow: '0 3px 0 rgba(0,0,0,0.85)',
    entranceAnimation: 'pop',
    animationLevel: 'word',
    wordActivation: 'pop',
    activeScale: 1.12,
    
    animationSpeed: 1.0,
    captionDepth: 'front',
    position: 'center',
  },

  // KARAOKE (from caption-templates)
  {
    id: 'karaoke',
    name: 'Karaoke',
    description: "Teleprompter style: the full line sits on a dark rounded pill, past words dim out and the current word glows.",
    category: 'Viral',
    fontFamily: "'Inter', sans-serif",
    fontWeight: 600,
    fontStyle: 'normal',
    textTransform: 'none',
    baseColor: '#f5f5f5',
    baseSize: 140,
    baseOpacity: 0.35,
    heroColor: '#7DF9FF',
    heroScale: 1.06,
    heroFontWeight: 600,
    heroFontStyle: 'normal',
    accentColor: '#7DF9FF',
    alignment: 'center',
    layoutType: 'subtitle-highlight',
    letterSpacing: '0.01em',
    lineHeight: 1.4,
    shadow: '0 2px 8px rgba(0,0,0,0.6)',
    entranceAnimation: 'fade',
    animationLevel: 'word',
    wordActivation: 'color-fill',
    
    animationSpeed: 1.0,
    captionDepth: 'front',
    position: 'bottom',
  },

  // KARAOKE FILL (from caption-templates)
  {
    id: 'karaoke-fill',
    name: 'Karaoke Fill',
    description: "The active word fills with a bright color that sweeps left to right, like a karaoke highlighter.",
    category: 'Viral',
    fontFamily: "'Inter', sans-serif",
    fontWeight: 700,
    fontStyle: 'normal',
    textTransform: 'none',
    baseColor: '#ffffff',
    baseSize: 140,
    baseOpacity: 1,
    heroColor: '#FFE500',
    heroScale: 1,
    heroFontWeight: 700,
    heroFontStyle: 'normal',
    accentColor: '#FFE500',
    alignment: 'center',
    layoutType: 'subtitle-highlight',
    letterSpacing: '0.01em',
    lineHeight: 1.4,
    shadow: '0 2px 6px rgba(0,0,0,0.55)',
    entranceAnimation: 'fade',
    animationLevel: 'word',
    wordActivation: 'color-fill',
    
    animationSpeed: 1.0,
    captionDepth: 'front',
    position: 'bottom',
  },

  // FADE (from caption-templates)
  {
    id: 'fade',
    name: 'Fade',
    description: "Clean and calm: each caption block gently fades in as a whole. No word popping, just smooth.",
    category: 'Viral',
    fontFamily: "'Inter', sans-serif",
    fontWeight: 500,
    fontStyle: 'normal',
    textTransform: 'none',
    baseColor: '#ffffff',
    baseSize: 130,
    baseOpacity: 1,
    heroColor: '#ffffff',
    heroScale: 1.1,
    heroFontWeight: 500,
    heroFontStyle: 'normal',
    accentColor: '#ffffff',
    alignment: 'center',
    layoutType: 'inline',
    letterSpacing: '0.015em',
    lineHeight: 1.45,
    shadow: '0 2px 10px rgba(0,0,0,0.65)',
    entranceAnimation: 'fade',
    animationLevel: 'segment',
    wordActivation: 'scale-up',
    
    animationSpeed: 1.0,
    captionDepth: 'front',
    position: 'bottom',
  },

  // SPRING (from caption-templates)
  {
    id: 'spring',
    name: 'Spring',
    description: "Playful bounce: every word springs up from below the baseline into the caption window.",
    category: 'Viral',
    fontFamily: "'Inter', sans-serif",
    fontWeight: 800,
    fontStyle: 'normal',
    textTransform: 'uppercase',
    baseColor: '#ffffff',
    baseSize: 140,
    baseOpacity: 1,
    heroColor: '#A3E635',
    heroScale: 1.15,
    heroFontWeight: 800,
    heroFontStyle: 'normal',
    accentColor: '#A3E635',
    alignment: 'center',
    layoutType: 'inline',
    letterSpacing: '0.01em',
    lineHeight: 1.25,
    shadow: '0 4px 0 rgba(0,0,0,0.85)',
    entranceAnimation: 'spring-up',
    animationLevel: 'word',
    wordActivation: 'pop',
    activeScale: 1.12,
    
    animationSpeed: 1.0,
    captionDepth: 'front',
    position: 'center',
  },

  // HYPE (from caption-templates)
  {
    id: 'hype',
    name: 'Hype',
    description: "Maximum energy: the active word explodes bigger in a hot orange-red flash.",
    category: 'Viral',
    fontFamily: "'Anton', sans-serif",
    fontWeight: 400,
    fontStyle: 'normal',
    textTransform: 'uppercase',
    baseColor: '#ffffff',
    baseSize: 150,
    baseOpacity: 1,
    heroColor: '#FF4D00',
    heroScale: 1.35,
    heroFontWeight: 400,
    heroFontStyle: 'normal',
    accentColor: '#FF4D00',
    alignment: 'center',
    layoutType: 'inline',
    letterSpacing: '0.02em',
    lineHeight: 1.15,
    shadow: '0 5px 0 rgba(0,0,0,0.9)',
    entranceAnimation: 'pop',
    animationLevel: 'word',
    wordActivation: 'pop',
    activeScale: 1.12,
    
    animationSpeed: 1.0,
    captionDepth: 'front',
    position: 'center',
  },

  // HORMOZI (from caption-templates)
  {
    id: 'hormozi',
    name: 'Hormozi',
    description: "Large stacked uppercase captions in Alex Hormozi's style — the active word pops in yellow.",
    category: 'Viral',
    fontFamily: "'Anton', sans-serif",
    fontWeight: 400,
    fontStyle: 'normal',
    textTransform: 'uppercase',
    baseColor: '#ffffff',
    baseSize: 150,
    baseOpacity: 1,
    heroColor: '#FFE500',
    heroScale: 1.18,
    heroFontWeight: 400,
    heroFontStyle: 'normal',
    accentColor: '#FFE500',
    alignment: 'center',
    layoutType: 'inline',
    letterSpacing: '0.01em',
    lineHeight: 1.15,
    shadow: '0 4px 0 rgba(0,0,0,0.9)',
    entranceAnimation: 'pop',
    animationLevel: 'word',
    wordActivation: 'pop',
    activeScale: 1.12,
    
    animationSpeed: 1.0,
    captionDepth: 'front',
    position: 'center',
  },

  // MINIMAL (from caption-templates)
  {
    id: 'minimal',
    name: 'Minimal',
    description: "One clean line, soft shadow, no animation at all. The caption that never distracts.",
    category: 'Viral',
    fontFamily: "'Inter', sans-serif",
    fontWeight: 400,
    fontStyle: 'normal',
    textTransform: 'none',
    baseColor: '#ffffff',
    baseSize: 90,
    baseOpacity: 1,
    heroColor: '#ffffff',
    heroScale: 1.1,
    heroFontWeight: 400,
    heroFontStyle: 'normal',
    accentColor: '#ffffff',
    alignment: 'center',
    layoutType: 'inline',
    letterSpacing: '0.02em',
    lineHeight: 1.5,
    shadow: '0 1px 6px rgba(0,0,0,0.7)',
    entranceAnimation: 'none',
    animationLevel: 'word',
    wordActivation: 'scale-up',
    
    animationSpeed: 1.0,
    captionDepth: 'front',
    position: 'bottom',
  },

  // BOX HIGHLIGHT (from caption-templates)
  {
    id: 'box-highlight',
    name: 'Box Highlight',
    description: "The spoken word gets stamped inside a solid yellow box with black text — impossible to miss.",
    category: 'Viral',
    fontFamily: "'Inter', sans-serif",
    fontWeight: 800,
    fontStyle: 'normal',
    textTransform: 'uppercase',
    baseColor: '#ffffff',
    baseSize: 140,
    baseOpacity: 1,
    heroColor: '#111111',
    heroScale: 1.12,
    heroFontWeight: 800,
    heroFontStyle: 'normal',
    accentColor: '#111111',
    alignment: 'center',
    layoutType: 'inline',
    letterSpacing: '0.01em',
    lineHeight: 1.35,
    shadow: '0 3px 0 rgba(0,0,0,0.85)',
    entranceAnimation: 'pop',
    animationLevel: 'word',
    wordActivation: 'highlight',
    highlightColor: '#FFE500', highlightPadX: 12, highlightPadY: 4, highlightRadius: 8,
    animationSpeed: 1.0,
    captionDepth: 'front',
    position: 'center',
  },

  // COMIC (from caption-templates)
  {
    id: 'comic',
    name: 'Comic',
    description: "Chunky comic-book lettering on a white speech bubble, tilted for attitude. POW!",
    category: 'Viral',
    fontFamily: "'Bangers', cursive",
    fontWeight: 400,
    fontStyle: 'normal',
    textTransform: 'uppercase',
    baseColor: '#111111',
    baseSize: 140,
    baseOpacity: 1,
    heroColor: '#FF3D00',
    heroScale: 1.25,
    heroFontWeight: 400,
    heroFontStyle: 'normal',
    accentColor: '#FF3D00',
    alignment: 'center',
    layoutType: 'inline',
    letterSpacing: '0.03em',
    lineHeight: 1.2,
    shadow: '4px 4px 0 rgba(0,0,0,1)',
    entranceAnimation: 'bounce',
    animationLevel: 'word',
    wordActivation: 'scale-up',
    
    animationSpeed: 1.0,
    captionDepth: 'front',
    position: 'center',
  },

  // PILL (from caption-templates)
  {
    id: 'pill',
    name: 'Pill',
    description: "The active word slips into a clean white pill badge while the rest stays ghosted white.",
    category: 'Viral',
    fontFamily: "'Inter', sans-serif",
    fontWeight: 700,
    fontStyle: 'normal',
    textTransform: 'none',
    baseColor: '#ffffff',
    baseSize: 130,
    baseOpacity: 1,
    heroColor: '#111111',
    heroScale: 1.1,
    heroFontWeight: 700,
    heroFontStyle: 'normal',
    accentColor: '#111111',
    alignment: 'center',
    layoutType: 'inline',
    letterSpacing: '0.01em',
    lineHeight: 1.5,
    shadow: '0 2px 8px rgba(0,0,0,0.7)',
    entranceAnimation: 'pop',
    animationLevel: 'word',
    wordActivation: 'highlight',
    highlightColor: '#ffffff', highlightPadX: 12, highlightPadY: 4, highlightRadius: 8,
    animationSpeed: 1.0,
    captionDepth: 'front',
    position: 'center',
  },

  // SCRIPT (from caption-templates)
  {
    id: 'script',
    name: 'Script',
    description: "Elegant flowing script lettering — lifestyle, beauty and vlog captions with a personal touch.",
    category: 'Viral',
    fontFamily: "'Pacifico', cursive",
    fontWeight: 400,
    fontStyle: 'normal',
    textTransform: 'none',
    baseColor: '#ffffff',
    baseSize: 110,
    baseOpacity: 1,
    heroColor: '#FFC2D4',
    heroScale: 1.15,
    heroFontWeight: 400,
    heroFontStyle: 'normal',
    accentColor: '#FFC2D4',
    alignment: 'center',
    layoutType: 'inline',
    letterSpacing: '0.01em',
    lineHeight: 1.35,
    shadow: '0 3px 10px rgba(0,0,0,0.75)',
    entranceAnimation: 'fade',
    animationLevel: 'word',
    wordActivation: 'scale-up',
    
    animationSpeed: 1.0,
    captionDepth: 'front',
    position: 'center',
  },

  // HANDWRITTEN (from caption-templates)
  {
    id: 'handwritten',
    name: 'Handwritten',
    description: "Casual marker handwriting, like a friend scribbled notes over your video.",
    category: 'Viral',
    fontFamily: "'Caveat', cursive",
    fontWeight: 700,
    fontStyle: 'normal',
    textTransform: 'none',
    baseColor: '#FFF8E7',
    baseSize: 110,
    baseOpacity: 1,
    heroColor: '#FFD166',
    heroScale: 1.18,
    heroFontWeight: 700,
    heroFontStyle: 'normal',
    accentColor: '#FFD166',
    alignment: 'center',
    layoutType: 'inline',
    letterSpacing: '0.01em',
    lineHeight: 1.25,
    shadow: '0 2px 6px rgba(0,0,0,0.7)',
    entranceAnimation: 'pop',
    animationLevel: 'word',
    wordActivation: 'scale-up',
    
    animationSpeed: 1.0,
    captionDepth: 'front',
    position: 'bottom',
  },

  // SINGLE WORD (from caption-templates)
  {
    id: 'single-word',
    name: 'Single Word',
    description: "One giant word at a time, dead center — the punchiest caption style on the internet.",
    category: 'Viral',
    fontFamily: "'Anton', sans-serif",
    fontWeight: 400,
    fontStyle: 'normal',
    textTransform: 'uppercase',
    baseColor: '#ffffff',
    baseSize: 170,
    baseOpacity: 1,
    heroColor: '#FFE500',
    heroScale: 1,
    heroFontWeight: 400,
    heroFontStyle: 'normal',
    accentColor: '#FFE500',
    alignment: 'center',
    layoutType: 'inline',
    letterSpacing: '0.02em',
    lineHeight: 1.1,
    shadow: '0 6px 0 rgba(0,0,0,0.9)',
    entranceAnimation: 'zoom-in',
    animationLevel: 'word',
    wordActivation: 'scale-up',
    
    animationSpeed: 1.0,
    captionDepth: 'front',
    position: 'center',
  },

  // NEON GLOW (from caption-templates)
  {
    id: 'neon-glow',
    name: 'Neon Glow',
    description: "Midnight pill with electric neon words — the current word flickers on in cyan.",
    category: 'Viral',
    fontFamily: "'Space Grotesk', sans-serif",
    fontWeight: 700,
    fontStyle: 'normal',
    textTransform: 'uppercase',
    baseColor: '#e8faff',
    baseSize: 140,
    baseOpacity: 0.45,
    heroColor: '#00F5FF',
    heroScale: 1.12,
    heroFontWeight: 700,
    heroFontStyle: 'normal',
    accentColor: '#00F5FF',
    alignment: 'center',
    layoutType: 'inline',
    letterSpacing: '0.06em',
    lineHeight: 1.4,
    shadow: 'none',
    entranceAnimation: 'fade',
    animationLevel: 'word',
    wordActivation: 'scale-up',
    
    animationSpeed: 1.0,
    captionDepth: 'front',
    position: 'bottom',
  },

  // GRADIENT (from caption-templates)
  {
    id: 'gradient',
    name: 'Gradient',
    description: "Living gradient text that shimmers through pink, violet and mint while the active word pops.",
    category: 'Viral',
    fontFamily: "'Anton', sans-serif",
    fontWeight: 400,
    fontStyle: 'normal',
    textTransform: 'uppercase',
    baseColor: '#ffffff',
    baseSize: 140,
    baseOpacity: 1,
    heroColor: '#ffffff',
    heroScale: 1.18,
    heroFontWeight: 400,
    heroFontStyle: 'normal',
    accentColor: '#ffffff',
    alignment: 'center',
    layoutType: 'inline',
    letterSpacing: '0.02em',
    lineHeight: 1.2,
    shadow: '0 3px 12px rgba(0,0,0,0.6)',
    entranceAnimation: 'pop',
    animationLevel: 'word',
    wordActivation: 'scale-up',
    
    animationSpeed: 1.0,
    captionDepth: 'front',
    position: 'center',
  },

  // HIGHLIGHTER (from caption-templates)
  {
    id: 'highlighter',
    name: 'Highlighter',
    description: "A translucent yellow marker swipes behind the spoken word, like you studied your own video.",
    category: 'Viral',
    fontFamily: "'Inter', sans-serif",
    fontWeight: 800,
    fontStyle: 'normal',
    textTransform: 'uppercase',
    baseColor: '#ffffff',
    baseSize: 140,
    baseOpacity: 1,
    heroColor: '#ffffff',
    heroScale: 1.1,
    heroFontWeight: 800,
    heroFontStyle: 'normal',
    accentColor: '#ffffff',
    alignment: 'center',
    layoutType: 'inline',
    letterSpacing: '0.01em',
    lineHeight: 1.5,
    shadow: '0 3px 0 rgba(0,0,0,0.85)',
    entranceAnimation: 'fade',
    animationLevel: 'word',
    wordActivation: 'scale-up',
    
    animationSpeed: 1.0,
    captionDepth: 'front',
    position: 'center',
  },

  // UNDERLINE (from caption-templates)
  {
    id: 'underline',
    name: 'Underline',
    description: "A thick hand-drawn underline sweeps beneath each spoken word in hot coral.",
    category: 'Viral',
    fontFamily: "'Inter', sans-serif",
    fontWeight: 700,
    fontStyle: 'normal',
    textTransform: 'none',
    baseColor: '#ffffff',
    baseSize: 140,
    baseOpacity: 1,
    heroColor: '#FF6B6B',
    heroScale: 1.12,
    heroFontWeight: 700,
    heroFontStyle: 'normal',
    accentColor: '#FF6B6B',
    alignment: 'center',
    layoutType: 'inline',
    letterSpacing: '0.01em',
    lineHeight: 1.6,
    shadow: '0 2px 8px rgba(0,0,0,0.7)',
    entranceAnimation: 'fade',
    animationLevel: 'word',
    wordActivation: 'scale-up',
    
    animationSpeed: 1.0,
    captionDepth: 'front',
    position: 'center',
  },

  // GLIDE (from caption-templates)
  {
    id: 'glide',
    name: 'Glide',
    description: "Words glide in smoothly from the right as they are spoken — sleek and modern.",
    category: 'Viral',
    fontFamily: "'Inter', sans-serif",
    fontWeight: 700,
    fontStyle: 'normal',
    textTransform: 'uppercase',
    baseColor: '#ffffff',
    baseSize: 140,
    baseOpacity: 1,
    heroColor: '#7DF9FF',
    heroScale: 1.1,
    heroFontWeight: 700,
    heroFontStyle: 'normal',
    accentColor: '#7DF9FF',
    alignment: 'center',
    layoutType: 'inline',
    letterSpacing: '0.02em',
    lineHeight: 1.3,
    shadow: '0 3px 0 rgba(0,0,0,0.85)',
    entranceAnimation: 'fade',
    animationLevel: 'word',
    wordActivation: 'scale-up',
    
    animationSpeed: 1.0,
    captionDepth: 'front',
    position: 'center',
  },

  // CAPTION BAR (from caption-templates)
  {
    id: 'caption-bar',
    name: 'Caption Bar',
    description: "Solid full-width bottom strip, podcast style — maximum readability on any footage.",
    category: 'Viral',
    fontFamily: "'Inter', sans-serif",
    fontWeight: 600,
    fontStyle: 'normal',
    textTransform: 'none',
    baseColor: '#ffffff',
    baseSize: 100,
    baseOpacity: 1,
    heroColor: '#ffffff',
    heroScale: 1.1,
    heroFontWeight: 600,
    heroFontStyle: 'normal',
    accentColor: '#ffffff',
    alignment: 'center',
    layoutType: 'inline',
    letterSpacing: '0.01em',
    lineHeight: 1.45,
    shadow: 'none',
    entranceAnimation: 'fade',
    animationLevel: 'segment',
    wordActivation: 'scale-up',
    
    animationSpeed: 1.0,
    captionDepth: 'front',
    position: 'bottom',
  },

  // OUTLINE (from caption-templates)
  {
    id: 'outline',
    name: 'Outline',
    description: "Hollow outline type where the spoken word fills solid yellow — striking on dark footage.",
    category: 'Viral',
    fontFamily: "'Anton', sans-serif",
    fontWeight: 400,
    fontStyle: 'normal',
    textTransform: 'uppercase',
    baseColor: 'transparent',
    baseSize: 140,
    baseOpacity: 1,
    heroColor: '#FFE500',
    heroScale: 1.15,
    heroFontWeight: 400,
    heroFontStyle: 'normal',
    accentColor: '#FFE500',
    alignment: 'center',
    layoutType: 'inline',
    letterSpacing: '0.03em',
    lineHeight: 1.2,
    shadow: 'none',
    entranceAnimation: 'pop',
    animationLevel: 'word',
    wordActivation: 'scale-up',
    
    animationSpeed: 1.0,
    captionDepth: 'front',
    position: 'center',
  },

  // GLITCH (from caption-templates)
  {
    id: 'glitch',
    name: 'Glitch',
    description: "RGB-split digital glitch tears across the active word — pure cyberpunk energy.",
    category: 'Viral',
    fontFamily: "'Space Mono', monospace",
    fontWeight: 700,
    fontStyle: 'normal',
    textTransform: 'uppercase',
    baseColor: '#ffffff',
    baseSize: 140,
    baseOpacity: 0.85,
    heroColor: '#ffffff',
    heroScale: 1.1,
    heroFontWeight: 700,
    heroFontStyle: 'normal',
    accentColor: '#ffffff',
    alignment: 'center',
    layoutType: 'inline',
    letterSpacing: '0.04em',
    lineHeight: 1.3,
    shadow: '0 2px 0 rgba(0,0,0,0.8)',
    entranceAnimation: 'glitch',
    animationLevel: 'word',
    wordActivation: 'none',
    
    animationSpeed: 1.0,
    captionDepth: 'front',
    position: 'center',
  },

  // WAVE (from caption-templates)
  {
    id: 'wave',
    name: 'Wave',
    description: "Every word rides a continuous bouncing wave across the caption line. Impossible to ignore.",
    category: 'Viral',
    fontFamily: "'Inter', sans-serif",
    fontWeight: 800,
    fontStyle: 'normal',
    textTransform: 'uppercase',
    baseColor: '#ffffff',
    baseSize: 140,
    baseOpacity: 1,
    heroColor: '#FFE500',
    heroScale: 1.15,
    heroFontWeight: 800,
    heroFontStyle: 'normal',
    accentColor: '#FFE500',
    alignment: 'center',
    layoutType: 'inline',
    letterSpacing: '0.01em',
    lineHeight: 1.6,
    shadow: '0 3px 0 rgba(0,0,0,0.85)',
    entranceAnimation: 'fade',
    animationLevel: 'word',
    wordActivation: 'scale-up',
    
    animationSpeed: 1.0,
    captionDepth: 'front',
    position: 'center',
  },

  // STICKER (from caption-templates)
  {
    id: 'sticker',
    name: 'Sticker',
    description: "Die-cut sticker text with a thick white border, tilted -3 degrees and a hard offset shadow.",
    category: 'Viral',
    fontFamily: "'Anton', sans-serif",
    fontWeight: 400,
    fontStyle: 'normal',
    textTransform: 'uppercase',
    baseColor: '#FF4D8D',
    baseSize: 140,
    baseOpacity: 1,
    heroColor: '#FFD400',
    heroScale: 1.22,
    heroFontWeight: 400,
    heroFontStyle: 'normal',
    accentColor: '#FFD400',
    alignment: 'center',
    layoutType: 'inline',
    letterSpacing: '0.02em',
    lineHeight: 1.25,
    shadow: '6px 6px 0 rgba(0,0,0,1)',
    entranceAnimation: 'bounce',
    animationLevel: 'word',
    wordActivation: 'scale-up',
    
    animationSpeed: 1.0,
    captionDepth: 'front',
    position: 'center',
  },

  // FOCUS CARD (from caption-templates)
  {
    id: 'focus-card',
    name: 'Focus Card',
    description: "A frosted-glass card spotlights the active phrase while the rest of the line recedes.",
    category: 'Viral',
    fontFamily: "'Inter', sans-serif",
    fontWeight: 600,
    fontStyle: 'normal',
    textTransform: 'none',
    baseColor: '#ffffff',
    baseSize: 130,
    baseOpacity: 0.4,
    heroColor: '#FFE500',
    heroScale: 1.12,
    heroFontWeight: 600,
    heroFontStyle: 'normal',
    accentColor: '#FFE500',
    alignment: 'center',
    layoutType: 'inline',
    letterSpacing: '0.01em',
    lineHeight: 1.5,
    shadow: '0 2px 8px rgba(0,0,0,0.5)',
    entranceAnimation: 'pop',
    animationLevel: 'word',
    wordActivation: 'scale-up',
    
    animationSpeed: 1.0,
    captionDepth: 'front',
    position: 'center',
  },

  // PULSE (from caption-templates)
  {
    id: 'pulse',
    name: 'Pulse',
    description: "The spoken word gently pulses with a soft glow — calm emphasis that breathes with your voice.",
    category: 'Viral',
    fontFamily: "'Inter', sans-serif",
    fontWeight: 700,
    fontStyle: 'normal',
    textTransform: 'none',
    baseColor: '#ffffff',
    baseSize: 140,
    baseOpacity: 0.9,
    heroColor: '#C4B5FD',
    heroScale: 1.1,
    heroFontWeight: 700,
    heroFontStyle: 'normal',
    accentColor: '#C4B5FD',
    alignment: 'center',
    layoutType: 'inline',
    letterSpacing: '0.01em',
    lineHeight: 1.4,
    shadow: '0 2px 10px rgba(0,0,0,0.65)',
    entranceAnimation: 'fade',
    animationLevel: 'word',
    wordActivation: 'scale-up',
    
    animationSpeed: 1.0,
    captionDepth: 'front',
    position: 'center',
  },

  // ─── V2 VIRAL SET — distinctive high-craft styles ─────────────────────────

  // SYNE SURGE — ultra-bold display type, springy overshoot, electric lime
  {
    id: 'syne-surge',
    name: 'SYNE SURGE',
    description: 'Ultra-bold Syne display type with springy overshoot entrances and electric lime accents. Peak viral energy.',
    category: 'Viral',
    fontFamily: '"Syne", sans-serif',
    fontWeight: 800,
    fontStyle: 'normal',
    textTransform: 'uppercase',
    baseColor: '#ffffff',
    baseSize: 150,
    baseOpacity: 0.92,
    heroColor: '#c8ff00',
    heroScale: 2.4,
    heroFontWeight: 800,
    accentColor: '#c8ff00',
    alignment: 'center',
    layoutType: 'stacked',
    letterSpacing: '-0.02em',
    lineHeight: 1.0,
    shadow: '0px 6px 24px rgba(0,0,0,0.55)',
    entranceAnimation: 'spring-up',
    wordActivation: 'scale-up',
    animationSpeed: 0.8,
    captionDepth: 'front',
    position: 'bottom',
  },

  // TICKER — monospace news-ticker with sliding entrance
  {
    id: 'mono-ticker',
    name: 'TICKER',
    description: 'Monospace news-ticker captions with a sliding entrance and amber active-word fill.',
    category: 'Viral',
    fontFamily: '"JetBrains Mono", monospace',
    fontWeight: 700,
    fontStyle: 'normal',
    textTransform: 'uppercase',
    baseColor: '#e8e6df',
    baseSize: 64,
    baseOpacity: 0.85,
    heroColor: '#ffb000',
    heroScale: 1.5,
    heroFontWeight: 700,
    accentColor: '#ffb000',
    alignment: 'center',
    layoutType: 'cinematic',
    letterSpacing: '0.08em',
    lineHeight: 1.4,
    shadow: '0px 2px 10px rgba(0,0,0,0.6)',
    entranceAnimation: 'slide-right-to-left',
    wordActivation: 'color-fill',
    animationSpeed: 0.9,
    captionDepth: 'front',
    position: 'bottom',
  },

  // OUTLINE WIPE — hollow words that fill solid as spoken
  {
    id: 'outline-wipe',
    name: 'OUTLINE WIPE',
    description: 'Hollow outlined words that fill solid as they are spoken. Striking on dark footage.',
    category: 'Viral',
    fontFamily: '"Geist", sans-serif',
    fontWeight: 800,
    fontStyle: 'normal',
    textTransform: 'uppercase',
    baseColor: 'transparent',
    baseSize: 150,
    baseOpacity: 1,
    outline: '2px solid #ffffff',
    heroColor: '#ffffff',
    heroScale: 1.6,
    heroFontWeight: 800,
    accentColor: '#ffffff',
    alignment: 'center',
    layoutType: 'inline',
    letterSpacing: '0.01em',
    lineHeight: 1.15,
    shadow: 'none',
    entranceAnimation: 'fade-up',
    wordActivation: 'color-fill',
    animationSpeed: 1.0,
    captionDepth: 'front',
    position: 'center',
  },

  // GARAMOND NOIR — high-fashion serif italics, champagne on dark
  {
    id: 'gara-noir',
    name: 'GARAMOND NOIR',
    description: 'High-fashion serif italics in warm champagne with a slow soft reveal. Quiet luxury captions.',
    category: 'Viral',
    fontFamily: '"Cormorant Garamond", serif',
    fontWeight: 600,
    fontStyle: 'italic',
    textTransform: 'none',
    baseColor: '#f5e6c8',
    baseSize: 72,
    baseOpacity: 0.75,
    heroColor: '#ffffff',
    heroScale: 2.0,
    heroFontFamily: '"Playfair Display", serif',
    heroFontWeight: 700,
    heroFontStyle: 'italic',
    accentColor: '#e8c87a',
    alignment: 'center',
    layoutType: 'editorial',
    letterSpacing: '0.02em',
    lineHeight: 1.1,
    shadow: '0px 2px 14px rgba(0,0,0,0.5)',
    entranceAnimation: 'soft-reveal',
    wordActivation: 'color-fill',
    animationSpeed: 1.4,
    captionDepth: 'front',
    position: 'center',
  },

  // PUNCH ZOOM — words punch toward camera as they land
  {
    id: 'punch-zoom',
    name: 'PUNCH ZOOM',
    description: 'Each word punches toward the camera as it lands. Aggressive, high-retention pacing.',
    category: 'Viral',
    fontFamily: '"Plus Jakarta Sans", sans-serif',
    fontWeight: 800,
    fontStyle: 'normal',
    textTransform: 'uppercase',
    baseColor: '#ffffff',
    baseSize: 150,
    baseOpacity: 0.9,
    heroColor: '#ff3b30',
    heroScale: 1.9,
    heroFontWeight: 800,
    accentColor: '#ff3b30',
    alignment: 'center',
    layoutType: 'inline',
    letterSpacing: '-0.01em',
    lineHeight: 1.1,
    shadow: '0px 4px 16px rgba(0,0,0,0.6)',
    entranceAnimation: 'punch-in',
    wordActivation: 'pop',
    activeScale: 1.12,
    animationSpeed: 0.7,
    captionDepth: 'front',
    position: 'center',
  },

  // TYPEWRITER — raw mono, staggered entrance, phosphor green
  {
    id: 'typewriter',
    name: 'TYPEWRITER',
    description: 'Raw monospace captions with a staggered typewriter entrance and phosphor-green activation.',
    category: 'Viral',
    fontFamily: '"JetBrains Mono", monospace',
    fontWeight: 400,
    fontStyle: 'normal',
    textTransform: 'none',
    baseColor: '#d7d7d7',
    baseSize: 90,
    baseOpacity: 0.85,
    heroColor: '#00ff88',
    heroScale: 1.3,
    accentColor: '#00ff88',
    alignment: 'left',
    layoutType: 'inline',
    letterSpacing: '0.02em',
    lineHeight: 1.5,
    shadow: 'none',
    entranceAnimation: 'stagger',
    wordActivation: 'color-fill',
    animationSpeed: 1.0,
    captionDepth: 'front',
    position: 'bottom-left',
  },

  // PAPER CUT — bold editorial type with hard offset shadows
  {
    id: 'paper-cut',
    name: 'PAPER CUT',
    description: 'Bold editorial type with hard offset shadows, like cut paper laid on the screen.',
    category: 'Viral',
    fontFamily: '"Playfair Display", serif',
    fontWeight: 800,
    fontStyle: 'normal',
    textTransform: 'uppercase',
    baseColor: '#fffdf5',
    baseSize: 72,
    baseOpacity: 1,
    heroColor: '#ff4d00',
    heroScale: 2.2,
    heroFontWeight: 800,
    accentColor: '#ff4d00',
    alignment: 'center',
    layoutType: 'editorial',
    letterSpacing: '0',
    lineHeight: 1.0,
    shadow: '4px 4px 0px rgba(0,0,0,0.85)',
    entranceAnimation: 'rise',
    wordActivation: 'color-fill',
    animationSpeed: 0.9,
    captionDepth: 'front',
    position: 'center',
  },

  // VHS TRACKING — retro VHS with chromatic-split shadows
  {
    id: 'vhs-tracking',
    name: 'VHS TRACKING',
    description: 'Retro VHS captions with motion-blur entrances and cyan/magenta chromatic-split shadows.',
    category: 'Viral',
    fontFamily: '"JetBrains Mono", monospace',
    fontWeight: 700,
    fontStyle: 'normal',
    textTransform: 'uppercase',
    baseColor: '#e8f4f8',
    baseSize: 120,
    baseOpacity: 0.9,
    heroColor: '#00e5ff',
    heroScale: 1.5,
    heroFontWeight: 700,
    accentColor: '#ff2fb3',
    alignment: 'center',
    layoutType: 'cinematic',
    letterSpacing: '0.06em',
    lineHeight: 1.3,
    shadow: '2px 0 0 rgba(255,47,179,0.55), -2px 0 0 rgba(0,229,255,0.55)',
    entranceAnimation: 'motion-blur',
    wordActivation: 'color-fill',
    animationSpeed: 0.85,
    captionDepth: 'front',
    position: 'bottom',
  },

  // MARKER POP — spoken words slapped with a neon marker highlight
  {
    id: 'marker-pop',
    name: 'MARKER POP',
    description: 'Spoken words get slapped with a neon marker highlight. Impossible to ignore.',
    category: 'Viral',
    fontFamily: '"Plus Jakarta Sans", sans-serif',
    fontWeight: 800,
    fontStyle: 'normal',
    textTransform: 'none',
    baseColor: '#ffffff',
    baseSize: 140,
    baseOpacity: 0.92,
    heroColor: '#111111',
    heroScale: 1.15,
    heroFontWeight: 800,
    accentColor: '#d4ff00',
    highlightColor: '#d4ff00',
    highlightRadius: 6,
    highlightPadX: 12,
    highlightPadY: 4,
    alignment: 'center',
    layoutType: 'subtitle-highlight',
    letterSpacing: '-0.01em',
    lineHeight: 1.35,
    shadow: '0px 3px 12px rgba(0,0,0,0.55)',
    entranceAnimation: 'pop-in',
    wordActivation: 'highlight',
    animationSpeed: 0.8,
    captionDepth: 'front',
    position: 'bottom',
  },

  // KINETIC SLAM — massive words slam in with elastic physics
  {
    id: 'kinetic-slam',
    name: 'KINETIC SLAM',
    description: 'Massive condensed words slam in with elastic physics. Made for hooks and punchlines.',
    category: 'Viral',
    fontFamily: '"Syne", sans-serif',
    fontWeight: 800,
    fontStyle: 'normal',
    textTransform: 'uppercase',
    baseColor: '#ffffff',
    baseSize: 150,
    baseOpacity: 0.9,
    heroColor: '#ffffff',
    heroScale: 3.0,
    heroFontWeight: 800,
    accentColor: '#7c5cff',
    alignment: 'center',
    layoutType: 'kinetic',
    letterSpacing: '-0.03em',
    lineHeight: 0.95,
    shadow: '0px 8px 28px rgba(0,0,0,0.6)',
    entranceAnimation: 'elastic',
    heroEntranceAnimation: 'punch-in',
    wordActivation: 'pop',
    activeScale: 1.12,
    animationSpeed: 0.75,
    captionDepth: 'front',
    position: 'center',
  },

  // SOFT DREAM — dreamy blurred serif drifting into focus
  {
    id: 'soft-dream',
    name: 'SOFT DREAM',
    description: 'Dreamy blurred serif that drifts into focus. For aesthetic vlogs and slow cinema.',
    category: 'Viral',
    fontFamily: '"Cormorant Garamond", serif',
    fontWeight: 500,
    fontStyle: 'italic',
    textTransform: 'none',
    baseColor: '#efe9f5',
    baseSize: 130,
    baseOpacity: 0.7,
    heroColor: '#ffffff',
    heroScale: 1.7,
    heroFontWeight: 600,
    heroFontStyle: 'italic',
    accentColor: '#c4b5fd',
    alignment: 'center',
    layoutType: 'inline',
    letterSpacing: '0.03em',
    lineHeight: 1.25,
    shadow: 'none',
    entranceAnimation: 'blur-in',
    wordActivation: 'color-fill',
    animationSpeed: 1.6,
    captionDepth: 'front',
    position: 'center',
  },

  // SPLIT FLAP — airport departure-board captions
  {
    id: 'split-flap',
    name: 'SPLIT FLAP',
    description: 'Airport departure-board captions — spaced mono type on dark with a snappy entrance.',
    category: 'Viral',
    fontFamily: '"JetBrains Mono", monospace',
    fontWeight: 700,
    fontStyle: 'normal',
    textTransform: 'uppercase',
    baseColor: '#f2f2f2',
    baseSize: 140,
    baseOpacity: 0.95,
    heroColor: '#ffd60a',
    heroScale: 1.4,
    heroFontWeight: 700,
    accentColor: '#ffd60a',
    alignment: 'center',
    layoutType: 'stacked',
    letterSpacing: '0.12em',
    lineHeight: 1.6,
    shadow: '0px 2px 0px rgba(0,0,0,0.9)',
    entranceAnimation: 'snap-in',
    wordActivation: 'color-fill',
    animationSpeed: 0.85,
    captionDepth: 'front',
    position: 'center',
  },
);


// ─── ROUND 3 — authentic viral caption styles (sourced from the Submagic /
// videocaption.ai / invideo.ai ecosystem, Oct 2026 research) ───────────────
// Signatures: Montserrat/Inter Black 900, 7-9% frame-height sizing, thick
// black stroke, transient 1.0 -> 1.12 -> 1.0 active-word punch (~140ms),
// yellow #FFEB00 / volt #A3E635 accents, no exit animation feel.
TEMPLATES.push(
  {
    id: 'mont-hormozi',
    name: 'Hormozi Black',
    description: 'The canonical viral caption: Montserrat Black, all caps, yellow punch on the spoken word.',
    category: 'Viral',
    fontFamily: "'Montserrat', sans-serif",
    fontWeight: 900,
    fontStyle: 'normal',
    textTransform: 'uppercase',
    baseColor: '#ffffff',
    baseSize: 150,
    baseOpacity: 1,
    heroColor: '#FFEB00',
    heroScale: 1.0,
    heroFontWeight: 900,
    accentColor: '#FFEB00',
    alignment: 'center',
    layoutType: 'inline',
    letterSpacing: '0.01em',
    lineHeight: 1.18,
    shadow: '0 5px 0 rgba(0,0,0,0.9)',
    outline: '2px #000000',
    entranceAnimation: 'pop',
    animationLevel: 'word',
    wordActivation: 'pop',
    activeScale: 1.12,
    animationSpeed: 1.0,
    captionDepth: 'front',
    position: 'center',
  },
  {
    id: 'volt-podcast',
    name: 'Podcast Volt',
    description: 'Interview/talking-head energy: heavy white type, electric lime punch.',
    category: 'Viral',
    fontFamily: "'Inter', sans-serif",
    fontWeight: 800,
    fontStyle: 'normal',
    textTransform: 'uppercase',
    baseColor: '#ffffff',
    baseSize: 145,
    baseOpacity: 1,
    heroColor: '#A3E635',
    heroScale: 1.0,
    heroFontWeight: 800,
    accentColor: '#A3E635',
    alignment: 'center',
    layoutType: 'inline',
    letterSpacing: '0.005em',
    lineHeight: 1.2,
    shadow: '0 4px 0 rgba(0,0,0,0.9)',
    outline: '2px #000000',
    entranceAnimation: 'spring-up',
    animationLevel: 'word',
    wordActivation: 'pop',
    activeScale: 1.14,
    animationSpeed: 1.0,
    captionDepth: 'front',
    position: 'center',
  },
  {
    id: 'beast-cartoon',
    name: 'Beast Toon',
    description: 'MrBeast-style cartoon chaos: chunky Bangers type, yellow base, orange keyword punch.',
    category: 'Viral',
    fontFamily: "'Bangers', cursive",
    fontWeight: 400,
    fontStyle: 'normal',
    textTransform: 'uppercase',
    baseColor: '#FFFF00',
    baseSize: 155,
    baseOpacity: 1,
    heroColor: '#FF6600',
    heroScale: 1.05,
    accentColor: '#FF6600',
    alignment: 'center',
    layoutType: 'inline',
    letterSpacing: '0.03em',
    lineHeight: 1.1,
    shadow: '0 6px 0 rgba(0,0,0,1)',
    outline: '3px #000000',
    entranceAnimation: 'bounce',
    animationLevel: 'word',
    wordActivation: 'pop',
    activeScale: 1.15,
    animationSpeed: 1.1,
    captionDepth: 'front',
    position: 'center',
  },
  {
    id: 'crimson-box',
    name: 'Crimson Box Pop',
    description: "MrBeast's signature move: a crimson box pops in behind the spoken word.",
    category: 'Viral',
    fontFamily: "'Anton', sans-serif",
    fontWeight: 400,
    fontStyle: 'normal',
    textTransform: 'uppercase',
    baseColor: '#ffffff',
    baseSize: 145,
    baseOpacity: 1,
    heroColor: '#ffffff',
    heroScale: 1.0,
    accentColor: '#ffffff',
    alignment: 'center',
    layoutType: 'subtitle-highlight',
    letterSpacing: '0.02em',
    lineHeight: 1.25,
    shadow: '0 4px 0 rgba(0,0,0,0.85)',
    entranceAnimation: 'pop',
    animationLevel: 'word',
    wordActivation: 'highlight',
    highlightColor: '#DC2626',
    highlightRadius: 8,
    highlightPadX: 14,
    highlightPadY: 6,
    animationSpeed: 1.0,
    captionDepth: 'front',
    position: 'center',
  },
  {
    id: 'pill-slide',
    name: 'Pill Slide Karaoke',
    description: 'A soft pill tracks the spoken word, sliding word to word.',
    category: 'Viral',
    fontFamily: "'Inter', sans-serif",
    fontWeight: 700,
    fontStyle: 'normal',
    textTransform: 'none',
    baseColor: '#ffffff',
    baseSize: 130,
    baseOpacity: 0.92,
    heroColor: '#0A0A0A',
    heroScale: 1.0,
    heroFontWeight: 800,
    accentColor: '#0A0A0A',
    alignment: 'center',
    layoutType: 'subtitle-highlight',
    letterSpacing: '0em',
    lineHeight: 1.3,
    shadow: '0 2px 12px rgba(0,0,0,0.55)',
    entranceAnimation: 'fade-up',
    animationLevel: 'word',
    wordActivation: 'highlight',
    highlightColor: '#ffffff',
    highlightRadius: 999,
    highlightPadX: 16,
    highlightPadY: 8,
    animationSpeed: 1.0,
    captionDepth: 'front',
    position: 'center',
  },
  {
    id: 'neon-arcade',
    name: 'Neon Arcade',
    description: 'Gaming/tech vibe: cyan type with a magenta glow punch on the spoken word.',
    category: 'Viral',
    fontFamily: "'Space Grotesk', sans-serif",
    fontWeight: 700,
    fontStyle: 'normal',
    textTransform: 'uppercase',
    baseColor: '#22D3EE',
    baseSize: 140,
    baseOpacity: 1,
    heroColor: '#F43F5E',
    heroScale: 1.0,
    heroFontWeight: 700,
    accentColor: '#F43F5E',
    alignment: 'center',
    layoutType: 'inline',
    letterSpacing: '0.04em',
    lineHeight: 1.2,
    shadow: '0 0 22px rgba(244,63,94,0.65), 0 3px 0 rgba(0,0,0,0.9)',
    entranceAnimation: 'blur-in',
    animationLevel: 'word',
    wordActivation: 'pop',
    activeScale: 1.12,
    animationSpeed: 1.0,
    captionDepth: 'front',
    position: 'center',
  },
  {
    id: 'depth-titan',
    name: 'Titan Behind',
    description: 'invideo-style bold text behind the subject — huge type with depth.',
    category: 'Viral',
    fontFamily: "'Anton', sans-serif",
    fontWeight: 400,
    fontStyle: 'normal',
    textTransform: 'uppercase',
    baseColor: '#ffffff',
    baseSize: 190,
    baseOpacity: 1,
    heroColor: '#FFEB00',
    heroScale: 1.0,
    accentColor: '#FFEB00',
    alignment: 'center',
    layoutType: 'inline',
    letterSpacing: '0.01em',
    lineHeight: 1.05,
    shadow: '0 6px 0 rgba(0,0,0,0.9)',
    outline: '2px #000000',
    entranceAnimation: 'zoom-in',
    animationLevel: 'word',
    wordActivation: 'pop',
    activeScale: 1.1,
    animationSpeed: 1.0,
    captionDepth: 'behind-subject',
    position: 'center',
  },
  {
    id: 'mono-terminal',
    name: 'Terminal Pop',
    description: 'Retro-terminal mono with a snappy green punch — Space Mono, full size.',
    category: 'Viral',
    fontFamily: "'Space Mono', monospace",
    fontWeight: 700,
    fontStyle: 'normal',
    textTransform: 'uppercase',
    baseColor: '#E8E8E8',
    baseSize: 120,
    baseOpacity: 1,
    heroColor: '#00FF4C',
    heroScale: 1.0,
    heroFontWeight: 700,
    accentColor: '#00FF4C',
    alignment: 'center',
    layoutType: 'inline',
    letterSpacing: '0em',
    lineHeight: 1.25,
    shadow: '0 0 18px rgba(0,255,76,0.35), 0 3px 0 rgba(0,0,0,0.9)',
    entranceAnimation: 'snap-in',
    animationLevel: 'word',
    wordActivation: 'pop',
    activeScale: 1.12,
    animationSpeed: 1.0,
    captionDepth: 'front',
    position: 'center',
  },
);

// ─── CURATED DYNAMIC SET ─────────────────────────────────────────────────
// The studio's default "Dynamic" tab: fewer templates, each with a genuinely
// DISTINCT motion behavior (not color/font swaps). Order = display order.
export const CURATED_DYNAMIC_IDS: string[] = [
  'mont-hormozi',   // Hormozi Black — transient word punch, Montserrat 900
  'beast-cartoon',  // Beast Toon — cartoon bounce pop
  'kinetic-slam',   // Kinetic Slam — elastic slam
  'punch-zoom',     // Punch Zoom — punch-in zoom
  'crimson-box',    // Crimson Box Pop — box snaps behind word
  'pill-slide',     // Pill Slide — pill tracks the spoken word
  'karaoke',        // Box Karaoke — yellow box karaoke
  'karaoke-fill',   // Karaoke Fill — true text flood, no box
  'dynamic-marker', // Dynamic Marker — handwritten ink, yellow marker sweeps the spoken word
  'crimson-solo',   // Crimson Solo — giant red serif-italic, one word at a time
  'neon-arcade',    // Neon Arcade — blur-in neon pop
  'spring',         // Spring — spring-up pop
  'butter-up',      // Butter — spring-up, color only (smooth, no pop)
  'typewriter',     // Typewriter — letter-by-letter stagger
  'mono-terminal',  // Terminal Pop — snap-in mono punch
  'mono-ticker',    // Ticker — continuous scroll banner
  'glitch',         // Glitch — RGB-split tear-in
  'vhs-tracking',   // VHS Tracking — motion-blur cinematic
  'depth-titan',    // Titan Behind — giant type behind subject
  'paper-cut',      // Paper Cut — editorial rise
  'syne-surge',     // Syne Surge — stacked spring
  'decode',         // Decode — scrambling glyphs lock left to right
  'wave-dance',     // Wave Dance — perpetual per-character sine wave
  'flip-card',      // Flip Card — departures-board 3D flip
  'karaoke-bounce', // Karaoke Bounce — spoken word jumps on a spring
  'minimal',        // Minimal — calm, near-static
];

export function getCuratedTemplates(): TemplateDefinition[] {
  const byId = new Map(TEMPLATES.map(t => [t.id, t]));
  return CURATED_DYNAMIC_IDS.map(id => byId.get(id)).filter((t): t is TemplateDefinition => !!t);
}


// ─── ROUND 4 — videocaption.ai motion behaviors (sourced Oct 2026) ──────────
// Decode/Scramble, true per-character Wave, Flip Card entrance, and the
// karaoke Bounce (jump) sub-style. Each is a genuinely new motion behavior,
// not a color/font swap.
TEMPLATES.push(
  {
    id: 'decode',
    name: 'Decode',
    description: 'Matrix-style decode: words arrive as scrambling glyphs that lock into letters left to right.',
    category: 'Viral',
    fontFamily: "'Space Mono', monospace",
    fontWeight: 700,
    fontStyle: 'normal',
    textTransform: 'uppercase',
    baseColor: '#8b8b8b',
    baseSize: 120,
    baseOpacity: 1,
    heroColor: '#00FF4C',
    heroScale: 1.0,
    heroFontWeight: 700,
    accentColor: '#00FF4C',
    alignment: 'center',
    layoutType: 'inline',
    letterSpacing: '0.02em',
    lineHeight: 1.25,
    shadow: '0 0 18px rgba(0,255,76,0.35)',
    entranceAnimation: 'fade',
    animationLevel: 'word',
    wordActivation: 'scramble',
    animationSpeed: 1.0,
    captionDepth: 'front',
    position: 'center',
  },
  {
    id: 'wave-dance',
    name: 'Wave Dance',
    description: 'Characters dance in a perpetual sine wave, phase travelling left to right.',
    category: 'Viral',
    fontFamily: "'Inter', sans-serif",
    fontWeight: 800,
    fontStyle: 'normal',
    textTransform: 'none',
    baseColor: '#ffffff',
    baseSize: 140,
    baseOpacity: 1,
    heroColor: '#FFEB00',
    heroScale: 1.0,
    heroFontWeight: 800,
    accentColor: '#FFEB00',
    alignment: 'center',
    layoutType: 'inline',
    letterSpacing: '0em',
    lineHeight: 1.3,
    shadow: '0 4px 0 rgba(0,0,0,0.9)',
    outline: '2px #000000',
    entranceAnimation: 'fade-up',
    animationLevel: 'word',
    wordActivation: 'wave',
    animationSpeed: 1.0,
    captionDepth: 'front',
    position: 'center',
  },
  {
    id: 'flip-card',
    name: 'Flip Card',
    description: 'Departures-board flip: each word swings into view on a 3D flip with a punch.',
    category: 'Viral',
    fontFamily: "'Anton', sans-serif",
    fontWeight: 400,
    fontStyle: 'normal',
    textTransform: 'uppercase',
    baseColor: '#ffffff',
    baseSize: 145,
    baseOpacity: 1,
    heroColor: '#FFEB00',
    heroScale: 1.0,
    accentColor: '#FFEB00',
    alignment: 'center',
    layoutType: 'inline',
    letterSpacing: '0.02em',
    lineHeight: 1.15,
    shadow: '0 4px 0 rgba(0,0,0,0.9)',
    outline: '2px #000000',
    entranceAnimation: 'flip-in',
    animationLevel: 'word',
    wordActivation: 'pop',
    activeScale: 1.1,
    animationSpeed: 1.0,
    captionDepth: 'front',
    position: 'center',
  },
  {
    id: 'karaoke-bounce',
    name: 'Karaoke Bounce',
    description: 'The karaoke Bounce sub-style: the spoken word jumps on a spring.',
    category: 'Viral',
    fontFamily: "'Inter', sans-serif",
    fontWeight: 800,
    fontStyle: 'normal',
    textTransform: 'uppercase',
    baseColor: '#ffffff',
    baseSize: 140,
    baseOpacity: 1,
    heroColor: '#FFEB00',
    heroScale: 1.0,
    heroFontWeight: 800,
    accentColor: '#FFEB00',
    alignment: 'center',
    layoutType: 'inline',
    letterSpacing: '0.01em',
    lineHeight: 1.2,
    shadow: '0 4px 0 rgba(0,0,0,0.9)',
    outline: '2px #000000',
    entranceAnimation: 'fade-up',
    animationLevel: 'word',
    wordActivation: 'jump',
    animationSpeed: 1.0,
    captionDepth: 'front',
    position: 'center',
  },
);

export function getTemplate(id: string): TemplateDefinition {
  return TEMPLATES.find(t => t.id === id) || TEMPLATES[0];
}

// ─── ROUND 5 — invideo.ai dynamic marker captions (sourced Oct 2026) ─────────
// Handwritten ink + a yellow marker that highlights each spoken word as it
// lands (dark ink on the marker, white everywhere else), soft shadow for
// readability, lower-third placement. Original recreation of the viral
// "dynamic captions" look: word-by-word reveal, marker emphasis on keywords.
TEMPLATES.push(
  {
    id: 'dynamic-marker',
    name: 'Dynamic Marker',
    description: 'Handwritten captions with a yellow marker sweeping over each spoken word — dark ink on the marker, white everywhere else.',
    category: 'Viral',
    fontFamily: "'Caveat', cursive",
    fontWeight: 700,
    fontStyle: 'normal',
    textTransform: 'none',
    baseColor: '#ffffff',
    baseSize: 84,
    baseOpacity: 1,
    heroColor: '#161616',
    heroScale: 1.0,
    heroFontFamily: "'Caveat', cursive",
    heroFontWeight: 700,
    heroFontStyle: 'normal',
    accentColor: '#FFD60A',
    alignment: 'center',
    layoutType: 'subtitle-highlight',
    letterSpacing: '0.01em',
    lineHeight: 1.35,
    shadow: '0 2px 10px rgba(0,0,0,0.55)',
    entranceAnimation: 'fade',
    animationLevel: 'word',
    wordActivation: 'highlight',
    highlightColor: '#FFD60A',
    highlightRadius: 6,
    highlightPadX: 14,
    highlightPadY: 4,
    animationSpeed: 1.0,
    captionDepth: 'front',
    position: 'bottom',
  },
);

// ─── ROUND 6 — solo-word shout captions (sourced Oct 2026) ───────────────────
// Giant red serif-italic, one word at a time across the top — the punchy
// editorial shout style. Uses the new 'solo-word' layout: only the spoken
// word renders, popping in fresh on every word change.
TEMPLATES.push(
  {
    id: 'crimson-solo',
    name: 'Crimson Solo',
    description: 'One giant red serif-italic word at a time across the top — the punchy editorial shout.',
    category: 'Viral',
    fontFamily: '"Playfair Display", serif',
    fontWeight: 800,
    fontStyle: 'italic',
    textTransform: 'uppercase',
    baseColor: '#d42b2b',
    baseSize: 180,
    baseOpacity: 1,
    heroColor: '#d42b2b',
    heroScale: 1.0,
    heroFontFamily: '"Playfair Display", serif',
    heroFontWeight: 800,
    heroFontStyle: 'italic',
    accentColor: '#d42b2b',
    alignment: 'center',
    layoutType: 'solo-word',
    letterSpacing: '0.02em',
    lineHeight: 1.0,
    shadow: '0 4px 24px rgba(0,0,0,0.45)',
    entranceAnimation: 'pop',
    animationLevel: 'word',
    wordActivation: 'none',
    animationSpeed: 1.0,
    captionDepth: 'front',
    position: 'top',
  },
);

